// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock_store

import (
	"context"

	"github.com/jackc/pgx/v5"
	"github.com/shadiestgoat/bankDataDB/data"
	"github.com/shadiestgoat/bankDataDB/db/store"
	mock "github.com/stretchr/testify/mock"
)

// NewMockStore creates a new instance of MockStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStore {
	mock := &MockStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStore is an autogenerated mock type for the Store type
type MockStore struct {
	mock.Mock
}

type MockStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStore) EXPECT() *MockStore_Expecter {
	return &MockStore_Expecter{mock: &_m.Mock}
}

// CardsDelete provides a mock function for the type MockStore
func (_mock *MockStore) CardsDelete(ctx context.Context, userID string, iD string) (int64, error) {
	ret := _mock.Called(ctx, userID, iD)

	if len(ret) == 0 {
		panic("no return value specified for CardsDelete")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (int64, error)); ok {
		return returnFunc(ctx, userID, iD)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) int64); ok {
		r0 = returnFunc(ctx, userID, iD)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, userID, iD)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_CardsDelete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CardsDelete'
type MockStore_CardsDelete_Call struct {
	*mock.Call
}

// CardsDelete is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - iD string
func (_e *MockStore_Expecter) CardsDelete(ctx interface{}, userID interface{}, iD interface{}) *MockStore_CardsDelete_Call {
	return &MockStore_CardsDelete_Call{Call: _e.mock.On("CardsDelete", ctx, userID, iD)}
}

func (_c *MockStore_CardsDelete_Call) Run(run func(ctx context.Context, userID string, iD string)) *MockStore_CardsDelete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStore_CardsDelete_Call) Return(n int64, err error) *MockStore_CardsDelete_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockStore_CardsDelete_Call) RunAndReturn(run func(ctx context.Context, userID string, iD string) (int64, error)) *MockStore_CardsDelete_Call {
	_c.Call.Return(run)
	return _c
}

// CardsNew provides a mock function for the type MockStore
func (_mock *MockStore) CardsNew(ctx context.Context, userID string, name string) (string, error) {
	ret := _mock.Called(ctx, userID, name)

	if len(ret) == 0 {
		panic("no return value specified for CardsNew")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return returnFunc(ctx, userID, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = returnFunc(ctx, userID, name)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, userID, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_CardsNew_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CardsNew'
type MockStore_CardsNew_Call struct {
	*mock.Call
}

// CardsNew is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - name string
func (_e *MockStore_Expecter) CardsNew(ctx interface{}, userID interface{}, name interface{}) *MockStore_CardsNew_Call {
	return &MockStore_CardsNew_Call{Call: _e.mock.On("CardsNew", ctx, userID, name)}
}

func (_c *MockStore_CardsNew_Call) Run(run func(ctx context.Context, userID string, name string)) *MockStore_CardsNew_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStore_CardsNew_Call) Return(s string, err error) *MockStore_CardsNew_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockStore_CardsNew_Call) RunAndReturn(run func(ctx context.Context, userID string, name string) (string, error)) *MockStore_CardsNew_Call {
	_c.Call.Return(run)
	return _c
}

// CardsUpdate provides a mock function for the type MockStore
func (_mock *MockStore) CardsUpdate(ctx context.Context, userID string, iD string, name string) (int64, error) {
	ret := _mock.Called(ctx, userID, iD, name)

	if len(ret) == 0 {
		panic("no return value specified for CardsUpdate")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) (int64, error)); ok {
		return returnFunc(ctx, userID, iD, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) int64); ok {
		r0 = returnFunc(ctx, userID, iD, name)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = returnFunc(ctx, userID, iD, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_CardsUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CardsUpdate'
type MockStore_CardsUpdate_Call struct {
	*mock.Call
}

// CardsUpdate is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - iD string
//   - name string
func (_e *MockStore_Expecter) CardsUpdate(ctx interface{}, userID interface{}, iD interface{}, name interface{}) *MockStore_CardsUpdate_Call {
	return &MockStore_CardsUpdate_Call{Call: _e.mock.On("CardsUpdate", ctx, userID, iD, name)}
}

func (_c *MockStore_CardsUpdate_Call) Run(run func(ctx context.Context, userID string, iD string, name string)) *MockStore_CardsUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockStore_CardsUpdate_Call) Return(n int64, err error) *MockStore_CardsUpdate_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockStore_CardsUpdate_Call) RunAndReturn(run func(ctx context.Context, userID string, iD string, name string) (int64, error)) *MockStore_CardsUpdate_Call {
	_c.Call.Return(run)
	return _c
}

// CategoriesDelete provides a mock function for the type MockStore
func (_mock *MockStore) CategoriesDelete(ctx context.Context, authorID string, iD string) (int64, error) {
	ret := _mock.Called(ctx, authorID, iD)

	if len(ret) == 0 {
		panic("no return value specified for CategoriesDelete")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (int64, error)); ok {
		return returnFunc(ctx, authorID, iD)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) int64); ok {
		r0 = returnFunc(ctx, authorID, iD)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, authorID, iD)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_CategoriesDelete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CategoriesDelete'
type MockStore_CategoriesDelete_Call struct {
	*mock.Call
}

// CategoriesDelete is a helper method to define mock.On call
//   - ctx context.Context
//   - authorID string
//   - iD string
func (_e *MockStore_Expecter) CategoriesDelete(ctx interface{}, authorID interface{}, iD interface{}) *MockStore_CategoriesDelete_Call {
	return &MockStore_CategoriesDelete_Call{Call: _e.mock.On("CategoriesDelete", ctx, authorID, iD)}
}

func (_c *MockStore_CategoriesDelete_Call) Run(run func(ctx context.Context, authorID string, iD string)) *MockStore_CategoriesDelete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStore_CategoriesDelete_Call) Return(n int64, err error) *MockStore_CategoriesDelete_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockStore_CategoriesDelete_Call) RunAndReturn(run func(ctx context.Context, authorID string, iD string) (int64, error)) *MockStore_CategoriesDelete_Call {
	_c.Call.Return(run)
	return _c
}

// MappingGetAll provides a mock function for the type MockStore
func (_mock *MockStore) MappingGetAll(ctx context.Context, authorID string) ([]*data.Mapping, error) {
	ret := _mock.Called(ctx, authorID)

	if len(ret) == 0 {
		panic("no return value specified for MappingGetAll")
	}

	var r0 []*data.Mapping
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]*data.Mapping, error)); ok {
		return returnFunc(ctx, authorID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []*data.Mapping); ok {
		r0 = returnFunc(ctx, authorID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*data.Mapping)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, authorID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_MappingGetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MappingGetAll'
type MockStore_MappingGetAll_Call struct {
	*mock.Call
}

// MappingGetAll is a helper method to define mock.On call
//   - ctx context.Context
//   - authorID string
func (_e *MockStore_Expecter) MappingGetAll(ctx interface{}, authorID interface{}) *MockStore_MappingGetAll_Call {
	return &MockStore_MappingGetAll_Call{Call: _e.mock.On("MappingGetAll", ctx, authorID)}
}

func (_c *MockStore_MappingGetAll_Call) Run(run func(ctx context.Context, authorID string)) *MockStore_MappingGetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_MappingGetAll_Call) Return(mappings []*data.Mapping, err error) *MockStore_MappingGetAll_Call {
	_c.Call.Return(mappings, err)
	return _c
}

func (_c *MockStore_MappingGetAll_Call) RunAndReturn(run func(ctx context.Context, authorID string) ([]*data.Mapping, error)) *MockStore_MappingGetAll_Call {
	_c.Call.Return(run)
	return _c
}

// MappingGetByID provides a mock function for the type MockStore
func (_mock *MockStore) MappingGetByID(ctx context.Context, authorID string, mappingID string) (*data.Mapping, error) {
	ret := _mock.Called(ctx, authorID, mappingID)

	if len(ret) == 0 {
		panic("no return value specified for MappingGetByID")
	}

	var r0 *data.Mapping
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*data.Mapping, error)); ok {
		return returnFunc(ctx, authorID, mappingID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *data.Mapping); ok {
		r0 = returnFunc(ctx, authorID, mappingID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*data.Mapping)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, authorID, mappingID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_MappingGetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MappingGetByID'
type MockStore_MappingGetByID_Call struct {
	*mock.Call
}

// MappingGetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - authorID string
//   - mappingID string
func (_e *MockStore_Expecter) MappingGetByID(ctx interface{}, authorID interface{}, mappingID interface{}) *MockStore_MappingGetByID_Call {
	return &MockStore_MappingGetByID_Call{Call: _e.mock.On("MappingGetByID", ctx, authorID, mappingID)}
}

func (_c *MockStore_MappingGetByID_Call) Run(run func(ctx context.Context, authorID string, mappingID string)) *MockStore_MappingGetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStore_MappingGetByID_Call) Return(mapping *data.Mapping, err error) *MockStore_MappingGetByID_Call {
	_c.Call.Return(mapping, err)
	return _c
}

func (_c *MockStore_MappingGetByID_Call) RunAndReturn(run func(ctx context.Context, authorID string, mappingID string) (*data.Mapping, error)) *MockStore_MappingGetByID_Call {
	_c.Call.Return(run)
	return _c
}

// MappingsDeleteKeepingOrphans provides a mock function for the type MockStore
func (_mock *MockStore) MappingsDeleteKeepingOrphans(ctx context.Context, authorID string, iD string) (int64, error) {
	ret := _mock.Called(ctx, authorID, iD)

	if len(ret) == 0 {
		panic("no return value specified for MappingsDeleteKeepingOrphans")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (int64, error)); ok {
		return returnFunc(ctx, authorID, iD)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) int64); ok {
		r0 = returnFunc(ctx, authorID, iD)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, authorID, iD)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_MappingsDeleteKeepingOrphans_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MappingsDeleteKeepingOrphans'
type MockStore_MappingsDeleteKeepingOrphans_Call struct {
	*mock.Call
}

// MappingsDeleteKeepingOrphans is a helper method to define mock.On call
//   - ctx context.Context
//   - authorID string
//   - iD string
func (_e *MockStore_Expecter) MappingsDeleteKeepingOrphans(ctx interface{}, authorID interface{}, iD interface{}) *MockStore_MappingsDeleteKeepingOrphans_Call {
	return &MockStore_MappingsDeleteKeepingOrphans_Call{Call: _e.mock.On("MappingsDeleteKeepingOrphans", ctx, authorID, iD)}
}

func (_c *MockStore_MappingsDeleteKeepingOrphans_Call) Run(run func(ctx context.Context, authorID string, iD string)) *MockStore_MappingsDeleteKeepingOrphans_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStore_MappingsDeleteKeepingOrphans_Call) Return(n int64, err error) *MockStore_MappingsDeleteKeepingOrphans_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockStore_MappingsDeleteKeepingOrphans_Call) RunAndReturn(run func(ctx context.Context, authorID string, iD string) (int64, error)) *MockStore_MappingsDeleteKeepingOrphans_Call {
	_c.Call.Return(run)
	return _c
}

// MappingsDeleteNoOrphans provides a mock function for the type MockStore
func (_mock *MockStore) MappingsDeleteNoOrphans(ctx context.Context) ([]*store.MappingsDeleteNoOrphansRow, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for MappingsDeleteNoOrphans")
	}

	var r0 []*store.MappingsDeleteNoOrphansRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*store.MappingsDeleteNoOrphansRow, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*store.MappingsDeleteNoOrphansRow); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*store.MappingsDeleteNoOrphansRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_MappingsDeleteNoOrphans_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MappingsDeleteNoOrphans'
type MockStore_MappingsDeleteNoOrphans_Call struct {
	*mock.Call
}

// MappingsDeleteNoOrphans is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockStore_Expecter) MappingsDeleteNoOrphans(ctx interface{}) *MockStore_MappingsDeleteNoOrphans_Call {
	return &MockStore_MappingsDeleteNoOrphans_Call{Call: _e.mock.On("MappingsDeleteNoOrphans", ctx)}
}

func (_c *MockStore_MappingsDeleteNoOrphans_Call) Run(run func(ctx context.Context)) *MockStore_MappingsDeleteNoOrphans_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStore_MappingsDeleteNoOrphans_Call) Return(mappingsDeleteNoOrphansRows []*store.MappingsDeleteNoOrphansRow, err error) *MockStore_MappingsDeleteNoOrphans_Call {
	_c.Call.Return(mappingsDeleteNoOrphansRows, err)
	return _c
}

func (_c *MockStore_MappingsDeleteNoOrphans_Call) RunAndReturn(run func(ctx context.Context) ([]*store.MappingsDeleteNoOrphansRow, error)) *MockStore_MappingsDeleteNoOrphans_Call {
	_c.Call.Return(run)
	return _c
}

// MappingsExists provides a mock function for the type MockStore
func (_mock *MockStore) MappingsExists(ctx context.Context, authorID string, iD string) (bool, error) {
	ret := _mock.Called(ctx, authorID, iD)

	if len(ret) == 0 {
		panic("no return value specified for MappingsExists")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (bool, error)); ok {
		return returnFunc(ctx, authorID, iD)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = returnFunc(ctx, authorID, iD)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, authorID, iD)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_MappingsExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MappingsExists'
type MockStore_MappingsExists_Call struct {
	*mock.Call
}

// MappingsExists is a helper method to define mock.On call
//   - ctx context.Context
//   - authorID string
//   - iD string
func (_e *MockStore_Expecter) MappingsExists(ctx interface{}, authorID interface{}, iD interface{}) *MockStore_MappingsExists_Call {
	return &MockStore_MappingsExists_Call{Call: _e.mock.On("MappingsExists", ctx, authorID, iD)}
}

func (_c *MockStore_MappingsExists_Call) Run(run func(ctx context.Context, authorID string, iD string)) *MockStore_MappingsExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStore_MappingsExists_Call) Return(b bool, err error) *MockStore_MappingsExists_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockStore_MappingsExists_Call) RunAndReturn(run func(ctx context.Context, authorID string, iD string) (bool, error)) *MockStore_MappingsExists_Call {
	_c.Call.Return(run)
	return _c
}

// NewCategory provides a mock function for the type MockStore
func (_mock *MockStore) NewCategory(ctx context.Context, authorID string, name string, icon string, color string) (string, error) {
	ret := _mock.Called(ctx, authorID, name, icon, color)

	if len(ret) == 0 {
		panic("no return value specified for NewCategory")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string) (string, error)); ok {
		return returnFunc(ctx, authorID, name, icon, color)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string) string); ok {
		r0 = returnFunc(ctx, authorID, name, icon, color)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string, string) error); ok {
		r1 = returnFunc(ctx, authorID, name, icon, color)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_NewCategory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewCategory'
type MockStore_NewCategory_Call struct {
	*mock.Call
}

// NewCategory is a helper method to define mock.On call
//   - ctx context.Context
//   - authorID string
//   - name string
//   - icon string
//   - color string
func (_e *MockStore_Expecter) NewCategory(ctx interface{}, authorID interface{}, name interface{}, icon interface{}, color interface{}) *MockStore_NewCategory_Call {
	return &MockStore_NewCategory_Call{Call: _e.mock.On("NewCategory", ctx, authorID, name, icon, color)}
}

func (_c *MockStore_NewCategory_Call) Run(run func(ctx context.Context, authorID string, name string, icon string, color string)) *MockStore_NewCategory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockStore_NewCategory_Call) Return(s string, err error) *MockStore_NewCategory_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockStore_NewCategory_Call) RunAndReturn(run func(ctx context.Context, authorID string, name string, icon string, color string) (string, error)) *MockStore_NewCategory_Call {
	_c.Call.Return(run)
	return _c
}

// SendBatch provides a mock function for the type MockStore
func (_mock *MockStore) SendBatch(ctx context.Context, b *pgx.Batch) error {
	ret := _mock.Called(ctx, b)

	if len(ret) == 0 {
		panic("no return value specified for SendBatch")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *pgx.Batch) error); ok {
		r0 = returnFunc(ctx, b)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStore_SendBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendBatch'
type MockStore_SendBatch_Call struct {
	*mock.Call
}

// SendBatch is a helper method to define mock.On call
//   - ctx context.Context
//   - b *pgx.Batch
func (_e *MockStore_Expecter) SendBatch(ctx interface{}, b interface{}) *MockStore_SendBatch_Call {
	return &MockStore_SendBatch_Call{Call: _e.mock.On("SendBatch", ctx, b)}
}

func (_c *MockStore_SendBatch_Call) Run(run func(ctx context.Context, b *pgx.Batch)) *MockStore_SendBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *pgx.Batch
		if args[1] != nil {
			arg1 = args[1].(*pgx.Batch)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_SendBatch_Call) Return(err error) *MockStore_SendBatch_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStore_SendBatch_Call) RunAndReturn(run func(ctx context.Context, b *pgx.Batch) error) *MockStore_SendBatch_Call {
	_c.Call.Return(run)
	return _c
}

// TransactionsDelete provides a mock function for the type MockStore
func (_mock *MockStore) TransactionsDelete(ctx context.Context, authorID string, iD string) (int64, error) {
	ret := _mock.Called(ctx, authorID, iD)

	if len(ret) == 0 {
		panic("no return value specified for TransactionsDelete")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (int64, error)); ok {
		return returnFunc(ctx, authorID, iD)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) int64); ok {
		r0 = returnFunc(ctx, authorID, iD)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, authorID, iD)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_TransactionsDelete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TransactionsDelete'
type MockStore_TransactionsDelete_Call struct {
	*mock.Call
}

// TransactionsDelete is a helper method to define mock.On call
//   - ctx context.Context
//   - authorID string
//   - iD string
func (_e *MockStore_Expecter) TransactionsDelete(ctx interface{}, authorID interface{}, iD interface{}) *MockStore_TransactionsDelete_Call {
	return &MockStore_TransactionsDelete_Call{Call: _e.mock.On("TransactionsDelete", ctx, authorID, iD)}
}

func (_c *MockStore_TransactionsDelete_Call) Run(run func(ctx context.Context, authorID string, iD string)) *MockStore_TransactionsDelete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStore_TransactionsDelete_Call) Return(n int64, err error) *MockStore_TransactionsDelete_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockStore_TransactionsDelete_Call) RunAndReturn(run func(ctx context.Context, authorID string, iD string) (int64, error)) *MockStore_TransactionsDelete_Call {
	_c.Call.Return(run)
	return _c
}

// TxFunc provides a mock function for the type MockStore
func (_mock *MockStore) TxFunc(ctx context.Context, h func(s store.Store) error) error {
	ret := _mock.Called(ctx, h)

	if len(ret) == 0 {
		panic("no return value specified for TxFunc")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, func(s store.Store) error) error); ok {
		r0 = returnFunc(ctx, h)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStore_TxFunc_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TxFunc'
type MockStore_TxFunc_Call struct {
	*mock.Call
}

// TxFunc is a helper method to define mock.On call
//   - ctx context.Context
//   - h func(s store.Store) error
func (_e *MockStore_Expecter) TxFunc(ctx interface{}, h interface{}) *MockStore_TxFunc_Call {
	return &MockStore_TxFunc_Call{Call: _e.mock.On("TxFunc", ctx, h)}
}

func (_c *MockStore_TxFunc_Call) Run(run func(ctx context.Context, h func(s store.Store) error)) *MockStore_TxFunc_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 func(s store.Store) error
		if args[1] != nil {
			arg1 = args[1].(func(s store.Store) error)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_TxFunc_Call) Return(err error) *MockStore_TxFunc_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStore_TxFunc_Call) RunAndReturn(run func(ctx context.Context, h func(s store.Store) error) error) *MockStore_TxFunc_Call {
	_c.Call.Return(run)
	return _c
}
