// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: bank_data/mappings.proto

package mappings

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AmountMatchMode int32

const (
	AmountMatchModeExact AmountMatchMode = 0
	AmountMatchModeGt    AmountMatchMode = 1
	AmountMatchModeGte   AmountMatchMode = 2
	AmountMatchModeLt    AmountMatchMode = 3
	AmountMatchModeLte   AmountMatchMode = 4
)

// Enum value maps for AmountMatchMode.
var (
	AmountMatchMode_name = map[int32]string{
		0: "EXACT",
		1: "GT",
		2: "GTE",
		3: "LT",
		4: "LTE",
	}
	AmountMatchMode_value = map[string]int32{
		"EXACT": 0,
		"GT":    1,
		"GTE":   2,
		"LT":    3,
		"LTE":   4,
	}
)

func (x AmountMatchMode) Enum() *AmountMatchMode {
	p := new(AmountMatchMode)
	*p = x
	return p
}

func (x AmountMatchMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AmountMatchMode) Descriptor() protoreflect.EnumDescriptor {
	return file_bank_data_mappings_proto_enumTypes[0].Descriptor()
}

func (AmountMatchMode) Type() protoreflect.EnumType {
	return &file_bank_data_mappings_proto_enumTypes[0]
}

func (x AmountMatchMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type ReqList struct {
	state                      protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_PageSize        uint32                 `protobuf:"varint,1,opt,name=page_size,json=pageSize"`
	xxx_hidden_PaginationToken *string                `protobuf:"bytes,2,opt,name=pagination_token,json=paginationToken"`
	xxx_hidden_CardId          *string                `protobuf:"bytes,3,opt,name=card_id,json=cardId"`
	XXX_raceDetectHookData     protoimpl.RaceDetectHookData
	XXX_presence               [1]uint32
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *ReqList) Reset() {
	*x = ReqList{}
	mi := &file_bank_data_mappings_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqList) ProtoMessage() {}

func (x *ReqList) ProtoReflect() protoreflect.Message {
	mi := &file_bank_data_mappings_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ReqList) GetPageSize() uint32 {
	if x != nil {
		return x.xxx_hidden_PageSize
	}
	return 0
}

func (x *ReqList) GetPaginationToken() string {
	if x != nil {
		if x.xxx_hidden_PaginationToken != nil {
			return *x.xxx_hidden_PaginationToken
		}
		return ""
	}
	return ""
}

func (x *ReqList) GetCardID() string {
	if x != nil {
		if x.xxx_hidden_CardId != nil {
			return *x.xxx_hidden_CardId
		}
		return ""
	}
	return ""
}

func (x *ReqList) SetPageSize(v uint32) {
	x.xxx_hidden_PageSize = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *ReqList) SetPaginationToken(v string) {
	x.xxx_hidden_PaginationToken = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *ReqList) SetCardId(v string) {
	x.xxx_hidden_CardId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
}

func (x *ReqList) HasPageSize() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ReqList) HasPaginationToken() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *ReqList) HasCardId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *ReqList) ClearPageSize() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_PageSize = 0
}

func (x *ReqList) ClearPaginationToken() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_PaginationToken = nil
}

func (x *ReqList) ClearCardId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_CardId = nil
}

type ReqList_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	PageSize        *uint32
	PaginationToken *string
	// If specified, list only mappings that match against this specific card_id
	// Mappings that don't match against any card id are not returned.
	CardId *string
}

func (b0 ReqList_builder) Build() *ReqList {
	m0 := &ReqList{}
	b, x := &b0, m0
	_, _ = b, x
	if b.PageSize != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_PageSize = *b.PageSize
	}
	if b.PaginationToken != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_PaginationToken = b.PaginationToken
	}
	if b.CardId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_CardId = b.CardId
	}
	return m0
}

type RespList struct {
	state                      protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_TotalCount      uint32                 `protobuf:"varint,1,opt,name=total_count,json=totalCount"`
	xxx_hidden_PaginationToken *string                `protobuf:"bytes,2,opt,name=pagination_token,json=paginationToken"`
	xxx_hidden_Result          *[]*Mapping            `protobuf:"bytes,3,rep,name=result"`
	XXX_raceDetectHookData     protoimpl.RaceDetectHookData
	XXX_presence               [1]uint32
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *RespList) Reset() {
	*x = RespList{}
	mi := &file_bank_data_mappings_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespList) ProtoMessage() {}

func (x *RespList) ProtoReflect() protoreflect.Message {
	mi := &file_bank_data_mappings_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RespList) GetTotalCount() uint32 {
	if x != nil {
		return x.xxx_hidden_TotalCount
	}
	return 0
}

func (x *RespList) GetPaginationToken() string {
	if x != nil {
		if x.xxx_hidden_PaginationToken != nil {
			return *x.xxx_hidden_PaginationToken
		}
		return ""
	}
	return ""
}

func (x *RespList) GetResult() []*Mapping {
	if x != nil {
		if x.xxx_hidden_Result != nil {
			return *x.xxx_hidden_Result
		}
	}
	return nil
}

func (x *RespList) SetTotalCount(v uint32) {
	x.xxx_hidden_TotalCount = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *RespList) SetPaginationToken(v string) {
	x.xxx_hidden_PaginationToken = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *RespList) SetResult(v []*Mapping) {
	x.xxx_hidden_Result = &v
}

func (x *RespList) HasTotalCount() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *RespList) HasPaginationToken() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *RespList) ClearTotalCount() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_TotalCount = 0
}

func (x *RespList) ClearPaginationToken() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_PaginationToken = nil
}

type RespList_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	TotalCount      *uint32
	PaginationToken *string
	Result          []*Mapping
}

func (b0 RespList_builder) Build() *RespList {
	m0 := &RespList{}
	b, x := &b0, m0
	_, _ = b, x
	if b.TotalCount != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_TotalCount = *b.TotalCount
	}
	if b.PaginationToken != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_PaginationToken = b.PaginationToken
	}
	x.xxx_hidden_Result = &b.Result
	return m0
}

// A mapping automatically configures a transaction with a name, category id, or both
type ReqNew struct {
	state                       protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Name             *string                `protobuf:"bytes,2,opt,name=name"`
	xxx_hidden_ResultCategoryId *string                `protobuf:"bytes,3,opt,name=result_category_id,json=resultCategoryId"`
	xxx_hidden_ResultName       *string                `protobuf:"bytes,4,opt,name=result_name,json=resultName"`
	xxx_hidden_MatchText        *string                `protobuf:"bytes,5,opt,name=match_text,json=matchText"`
	xxx_hidden_MatchAmountMode  AmountMatchMode        `protobuf:"varint,6,opt,name=match_amount_mode,json=matchAmountMode,enum=mappings.AmountMatchMode"`
	xxx_hidden_MatchAmount      float64                `protobuf:"fixed64,7,opt,name=match_amount,json=matchAmount"`
	xxx_hidden_MatchCardId      *string                `protobuf:"bytes,8,opt,name=match_card_id,json=matchCardId"`
	xxx_hidden_Priority         int32                  `protobuf:"varint,9,opt,name=priority"`
	XXX_raceDetectHookData      protoimpl.RaceDetectHookData
	XXX_presence                [1]uint32
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *ReqNew) Reset() {
	*x = ReqNew{}
	mi := &file_bank_data_mappings_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqNew) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqNew) ProtoMessage() {}

func (x *ReqNew) ProtoReflect() protoreflect.Message {
	mi := &file_bank_data_mappings_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ReqNew) GetName() string {
	if x != nil {
		if x.xxx_hidden_Name != nil {
			return *x.xxx_hidden_Name
		}
		return ""
	}
	return ""
}

func (x *ReqNew) GetResultCategoryID() string {
	if x != nil {
		if x.xxx_hidden_ResultCategoryId != nil {
			return *x.xxx_hidden_ResultCategoryId
		}
		return ""
	}
	return ""
}

func (x *ReqNew) GetResultName() string {
	if x != nil {
		if x.xxx_hidden_ResultName != nil {
			return *x.xxx_hidden_ResultName
		}
		return ""
	}
	return ""
}

func (x *ReqNew) GetMatchText() string {
	if x != nil {
		if x.xxx_hidden_MatchText != nil {
			return *x.xxx_hidden_MatchText
		}
		return ""
	}
	return ""
}

func (x *ReqNew) GetMatchAmountMode() AmountMatchMode {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 4) {
			return x.xxx_hidden_MatchAmountMode
		}
	}
	return AmountMatchModeExact
}

func (x *ReqNew) GetMatchAmount() float64 {
	if x != nil {
		return x.xxx_hidden_MatchAmount
	}
	return 0
}

func (x *ReqNew) GetMatchCardID() string {
	if x != nil {
		if x.xxx_hidden_MatchCardId != nil {
			return *x.xxx_hidden_MatchCardId
		}
		return ""
	}
	return ""
}

func (x *ReqNew) GetPriority() int32 {
	if x != nil {
		return x.xxx_hidden_Priority
	}
	return 0
}

func (x *ReqNew) SetName(v string) {
	x.xxx_hidden_Name = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 8)
}

func (x *ReqNew) SetResultCategoryId(v string) {
	x.xxx_hidden_ResultCategoryId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 8)
}

func (x *ReqNew) SetResultName(v string) {
	x.xxx_hidden_ResultName = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 8)
}

func (x *ReqNew) SetMatchText(v string) {
	x.xxx_hidden_MatchText = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 8)
}

func (x *ReqNew) SetMatchAmountMode(v AmountMatchMode) {
	x.xxx_hidden_MatchAmountMode = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 8)
}

func (x *ReqNew) SetMatchAmount(v float64) {
	x.xxx_hidden_MatchAmount = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 8)
}

func (x *ReqNew) SetMatchCardId(v string) {
	x.xxx_hidden_MatchCardId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 6, 8)
}

func (x *ReqNew) SetPriority(v int32) {
	x.xxx_hidden_Priority = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 7, 8)
}

func (x *ReqNew) HasName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ReqNew) HasResultCategoryId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *ReqNew) HasResultName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *ReqNew) HasMatchText() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *ReqNew) HasMatchAmountMode() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *ReqNew) HasMatchAmount() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *ReqNew) HasMatchCardId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 6)
}

func (x *ReqNew) HasPriority() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 7)
}

func (x *ReqNew) ClearName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Name = nil
}

func (x *ReqNew) ClearResultCategoryId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_ResultCategoryId = nil
}

func (x *ReqNew) ClearResultName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_ResultName = nil
}

func (x *ReqNew) ClearMatchText() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_MatchText = nil
}

func (x *ReqNew) ClearMatchAmountMode() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_MatchAmountMode = AmountMatchModeExact
}

func (x *ReqNew) ClearMatchAmount() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_MatchAmount = 0
}

func (x *ReqNew) ClearMatchCardId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 6)
	x.xxx_hidden_MatchCardId = nil
}

func (x *ReqNew) ClearPriority() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 7)
	x.xxx_hidden_Priority = 0
}

type ReqNew_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Name *string
	// If this mapping matches, what should be applied to the transaction?
	// At least 1 of name & category id is required
	ResultCategoryId *string
	ResultName       *string
	// Optionally match against the text of the transaction
	// Must be a POSIX Regex
	MatchText *string
	// Optionally match the amount using mode
	MatchAmountMode *AmountMatchMode
	MatchAmount     *float64
	// Optionally match of the card id
	MatchCardId *string
	// The matching priority of this matcher. The mappings with the highest priority get mapped first
	Priority *int32
}

func (b0 ReqNew_builder) Build() *ReqNew {
	m0 := &ReqNew{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Name != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 8)
		x.xxx_hidden_Name = b.Name
	}
	if b.ResultCategoryId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 8)
		x.xxx_hidden_ResultCategoryId = b.ResultCategoryId
	}
	if b.ResultName != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 8)
		x.xxx_hidden_ResultName = b.ResultName
	}
	if b.MatchText != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 8)
		x.xxx_hidden_MatchText = b.MatchText
	}
	if b.MatchAmountMode != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 8)
		x.xxx_hidden_MatchAmountMode = *b.MatchAmountMode
	}
	if b.MatchAmount != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 8)
		x.xxx_hidden_MatchAmount = *b.MatchAmount
	}
	if b.MatchCardId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 6, 8)
		x.xxx_hidden_MatchCardId = b.MatchCardId
	}
	if b.Priority != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 7, 8)
		x.xxx_hidden_Priority = *b.Priority
	}
	return m0
}

type RespNew struct {
	state                         protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id                 *string                `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_MappedTransactions uint32                 `protobuf:"varint,2,opt,name=mapped_transactions,json=mappedTransactions"`
	xxx_hidden_MappedNames        uint32                 `protobuf:"varint,3,opt,name=mapped_names,json=mappedNames"`
	xxx_hidden_MappedCategories   uint32                 `protobuf:"varint,4,opt,name=mapped_categories,json=mappedCategories"`
	XXX_raceDetectHookData        protoimpl.RaceDetectHookData
	XXX_presence                  [1]uint32
	unknownFields                 protoimpl.UnknownFields
	sizeCache                     protoimpl.SizeCache
}

func (x *RespNew) Reset() {
	*x = RespNew{}
	mi := &file_bank_data_mappings_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespNew) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespNew) ProtoMessage() {}

func (x *RespNew) ProtoReflect() protoreflect.Message {
	mi := &file_bank_data_mappings_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RespNew) GetID() string {
	if x != nil {
		if x.xxx_hidden_Id != nil {
			return *x.xxx_hidden_Id
		}
		return ""
	}
	return ""
}

func (x *RespNew) GetMappedTransactions() uint32 {
	if x != nil {
		return x.xxx_hidden_MappedTransactions
	}
	return 0
}

func (x *RespNew) GetMappedNames() uint32 {
	if x != nil {
		return x.xxx_hidden_MappedNames
	}
	return 0
}

func (x *RespNew) GetMappedCategories() uint32 {
	if x != nil {
		return x.xxx_hidden_MappedCategories
	}
	return 0
}

func (x *RespNew) SetId(v string) {
	x.xxx_hidden_Id = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 4)
}

func (x *RespNew) SetMappedTransactions(v uint32) {
	x.xxx_hidden_MappedTransactions = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 4)
}

func (x *RespNew) SetMappedNames(v uint32) {
	x.xxx_hidden_MappedNames = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 4)
}

func (x *RespNew) SetMappedCategories(v uint32) {
	x.xxx_hidden_MappedCategories = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 4)
}

func (x *RespNew) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *RespNew) HasMappedTransactions() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *RespNew) HasMappedNames() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *RespNew) HasMappedCategories() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *RespNew) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

func (x *RespNew) ClearMappedTransactions() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_MappedTransactions = 0
}

func (x *RespNew) ClearMappedNames() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_MappedNames = 0
}

func (x *RespNew) ClearMappedCategories() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_MappedCategories = 0
}

type RespNew_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id *string
	// Unique transaction count that this mapping mapped
	MappedTransactions *uint32
	// The number of transactions that had their name mapped
	MappedNames *uint32
	// the number of transactions that had their category mapped
	MappedCategories *uint32
}

func (b0 RespNew_builder) Build() *RespNew {
	m0 := &RespNew{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 4)
		x.xxx_hidden_Id = b.Id
	}
	if b.MappedTransactions != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 4)
		x.xxx_hidden_MappedTransactions = *b.MappedTransactions
	}
	if b.MappedNames != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 4)
		x.xxx_hidden_MappedNames = *b.MappedNames
	}
	if b.MappedCategories != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 4)
		x.xxx_hidden_MappedCategories = *b.MappedCategories
	}
	return m0
}

// A mapping automatically configures a transaction with a name, category id, or both
type Mapping struct {
	state                       protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id               *string                `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_Name             *string                `protobuf:"bytes,2,opt,name=name"`
	xxx_hidden_ResultCategoryId *string                `protobuf:"bytes,3,opt,name=result_category_id,json=resultCategoryId"`
	xxx_hidden_ResultName       *string                `protobuf:"bytes,4,opt,name=result_name,json=resultName"`
	xxx_hidden_MatchText        *string                `protobuf:"bytes,5,opt,name=match_text,json=matchText"`
	xxx_hidden_MatchAmountMode  AmountMatchMode        `protobuf:"varint,6,opt,name=match_amount_mode,json=matchAmountMode,enum=mappings.AmountMatchMode"`
	xxx_hidden_MatchAmount      float64                `protobuf:"fixed64,7,opt,name=match_amount,json=matchAmount"`
	xxx_hidden_MatchCardId      *string                `protobuf:"bytes,8,opt,name=match_card_id,json=matchCardId"`
	xxx_hidden_Priority         int32                  `protobuf:"varint,9,opt,name=priority"`
	XXX_raceDetectHookData      protoimpl.RaceDetectHookData
	XXX_presence                [1]uint32
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *Mapping) Reset() {
	*x = Mapping{}
	mi := &file_bank_data_mappings_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Mapping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mapping) ProtoMessage() {}

func (x *Mapping) ProtoReflect() protoreflect.Message {
	mi := &file_bank_data_mappings_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Mapping) GetID() string {
	if x != nil {
		if x.xxx_hidden_Id != nil {
			return *x.xxx_hidden_Id
		}
		return ""
	}
	return ""
}

func (x *Mapping) GetName() string {
	if x != nil {
		if x.xxx_hidden_Name != nil {
			return *x.xxx_hidden_Name
		}
		return ""
	}
	return ""
}

func (x *Mapping) GetResultCategoryID() string {
	if x != nil {
		if x.xxx_hidden_ResultCategoryId != nil {
			return *x.xxx_hidden_ResultCategoryId
		}
		return ""
	}
	return ""
}

func (x *Mapping) GetResultName() string {
	if x != nil {
		if x.xxx_hidden_ResultName != nil {
			return *x.xxx_hidden_ResultName
		}
		return ""
	}
	return ""
}

func (x *Mapping) GetMatchText() string {
	if x != nil {
		if x.xxx_hidden_MatchText != nil {
			return *x.xxx_hidden_MatchText
		}
		return ""
	}
	return ""
}

func (x *Mapping) GetMatchAmountMode() AmountMatchMode {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 5) {
			return x.xxx_hidden_MatchAmountMode
		}
	}
	return AmountMatchModeExact
}

func (x *Mapping) GetMatchAmount() float64 {
	if x != nil {
		return x.xxx_hidden_MatchAmount
	}
	return 0
}

func (x *Mapping) GetMatchCardID() string {
	if x != nil {
		if x.xxx_hidden_MatchCardId != nil {
			return *x.xxx_hidden_MatchCardId
		}
		return ""
	}
	return ""
}

func (x *Mapping) GetPriority() int32 {
	if x != nil {
		return x.xxx_hidden_Priority
	}
	return 0
}

func (x *Mapping) SetId(v string) {
	x.xxx_hidden_Id = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 9)
}

func (x *Mapping) SetName(v string) {
	x.xxx_hidden_Name = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 9)
}

func (x *Mapping) SetResultCategoryId(v string) {
	x.xxx_hidden_ResultCategoryId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 9)
}

func (x *Mapping) SetResultName(v string) {
	x.xxx_hidden_ResultName = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 9)
}

func (x *Mapping) SetMatchText(v string) {
	x.xxx_hidden_MatchText = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 9)
}

func (x *Mapping) SetMatchAmountMode(v AmountMatchMode) {
	x.xxx_hidden_MatchAmountMode = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 9)
}

func (x *Mapping) SetMatchAmount(v float64) {
	x.xxx_hidden_MatchAmount = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 6, 9)
}

func (x *Mapping) SetMatchCardId(v string) {
	x.xxx_hidden_MatchCardId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 7, 9)
}

func (x *Mapping) SetPriority(v int32) {
	x.xxx_hidden_Priority = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 8, 9)
}

func (x *Mapping) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Mapping) HasName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *Mapping) HasResultCategoryId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *Mapping) HasResultName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *Mapping) HasMatchText() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *Mapping) HasMatchAmountMode() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *Mapping) HasMatchAmount() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 6)
}

func (x *Mapping) HasMatchCardId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 7)
}

func (x *Mapping) HasPriority() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 8)
}

func (x *Mapping) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

func (x *Mapping) ClearName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Name = nil
}

func (x *Mapping) ClearResultCategoryId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_ResultCategoryId = nil
}

func (x *Mapping) ClearResultName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_ResultName = nil
}

func (x *Mapping) ClearMatchText() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_MatchText = nil
}

func (x *Mapping) ClearMatchAmountMode() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_MatchAmountMode = AmountMatchModeExact
}

func (x *Mapping) ClearMatchAmount() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 6)
	x.xxx_hidden_MatchAmount = 0
}

func (x *Mapping) ClearMatchCardId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 7)
	x.xxx_hidden_MatchCardId = nil
}

func (x *Mapping) ClearPriority() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 8)
	x.xxx_hidden_Priority = 0
}

type Mapping_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The ID of the mapping.
	Id *string
	// The name of the mapping (different from result_name)
	Name *string
	// If this mapping matches, what should be applied to the transaction?
	// At least 1 of name & category id is required
	ResultCategoryId *string
	ResultName       *string
	// Optionally match against the text of the transaction
	// Must be a POSIX Regex
	MatchText *string
	// Optionally match the amount using mode
	MatchAmountMode *AmountMatchMode
	MatchAmount     *float64
	// Optionally match of the card id
	MatchCardId *string
	// The matching priority of this matcher. The mappings with the highest priority get mapped first
	Priority *int32
}

func (b0 Mapping_builder) Build() *Mapping {
	m0 := &Mapping{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 9)
		x.xxx_hidden_Id = b.Id
	}
	if b.Name != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 9)
		x.xxx_hidden_Name = b.Name
	}
	if b.ResultCategoryId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 9)
		x.xxx_hidden_ResultCategoryId = b.ResultCategoryId
	}
	if b.ResultName != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 9)
		x.xxx_hidden_ResultName = b.ResultName
	}
	if b.MatchText != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 9)
		x.xxx_hidden_MatchText = b.MatchText
	}
	if b.MatchAmountMode != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 9)
		x.xxx_hidden_MatchAmountMode = *b.MatchAmountMode
	}
	if b.MatchAmount != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 6, 9)
		x.xxx_hidden_MatchAmount = *b.MatchAmount
	}
	if b.MatchCardId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 7, 9)
		x.xxx_hidden_MatchCardId = b.MatchCardId
	}
	if b.Priority != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 8, 9)
		x.xxx_hidden_Priority = *b.Priority
	}
	return m0
}

type ReqDelete struct {
	state                         protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id                 *string                `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_OrphanTransactions bool                   `protobuf:"varint,2,opt,name=orphan_transactions,json=orphanTransactions"`
	XXX_raceDetectHookData        protoimpl.RaceDetectHookData
	XXX_presence                  [1]uint32
	unknownFields                 protoimpl.UnknownFields
	sizeCache                     protoimpl.SizeCache
}

func (x *ReqDelete) Reset() {
	*x = ReqDelete{}
	mi := &file_bank_data_mappings_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqDelete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqDelete) ProtoMessage() {}

func (x *ReqDelete) ProtoReflect() protoreflect.Message {
	mi := &file_bank_data_mappings_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ReqDelete) GetID() string {
	if x != nil {
		if x.xxx_hidden_Id != nil {
			return *x.xxx_hidden_Id
		}
		return ""
	}
	return ""
}

func (x *ReqDelete) GetOrphanTransactions() bool {
	if x != nil {
		return x.xxx_hidden_OrphanTransactions
	}
	return false
}

func (x *ReqDelete) SetId(v string) {
	x.xxx_hidden_Id = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *ReqDelete) SetOrphanTransactions(v bool) {
	x.xxx_hidden_OrphanTransactions = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *ReqDelete) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ReqDelete) HasOrphanTransactions() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *ReqDelete) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

func (x *ReqDelete) ClearOrphanTransactions() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_OrphanTransactions = false
}

type ReqDelete_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The ID to delete
	Id *string
	// If true, just delete transactions, but NOT unmap them.
	// Eg. if a transaction's category was mapping using this mapping,
	// if this is set to true the transaction's category will remain as is
	OrphanTransactions *bool
}

func (b0 ReqDelete_builder) Build() *ReqDelete {
	m0 := &ReqDelete{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Id = b.Id
	}
	if b.OrphanTransactions != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_OrphanTransactions = *b.OrphanTransactions
	}
	return m0
}

type RespDelete struct {
	state                           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_AffectedTransactions uint32                 `protobuf:"varint,1,opt,name=affected_transactions,json=affectedTransactions"`
	xxx_hidden_RemappedTransactions uint32                 `protobuf:"varint,2,opt,name=remapped_transactions,json=remappedTransactions"`
	XXX_raceDetectHookData          protoimpl.RaceDetectHookData
	XXX_presence                    [1]uint32
	unknownFields                   protoimpl.UnknownFields
	sizeCache                       protoimpl.SizeCache
}

func (x *RespDelete) Reset() {
	*x = RespDelete{}
	mi := &file_bank_data_mappings_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespDelete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespDelete) ProtoMessage() {}

func (x *RespDelete) ProtoReflect() protoreflect.Message {
	mi := &file_bank_data_mappings_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RespDelete) GetAffectedTransactions() uint32 {
	if x != nil {
		return x.xxx_hidden_AffectedTransactions
	}
	return 0
}

func (x *RespDelete) GetRemappedTransactions() uint32 {
	if x != nil {
		return x.xxx_hidden_RemappedTransactions
	}
	return 0
}

func (x *RespDelete) SetAffectedTransactions(v uint32) {
	x.xxx_hidden_AffectedTransactions = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *RespDelete) SetRemappedTransactions(v uint32) {
	x.xxx_hidden_RemappedTransactions = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *RespDelete) HasAffectedTransactions() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *RespDelete) HasRemappedTransactions() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *RespDelete) ClearAffectedTransactions() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_AffectedTransactions = 0
}

func (x *RespDelete) ClearRemappedTransactions() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_RemappedTransactions = 0
}

type RespDelete_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The number of transactions that the deletion affected.
	// Will always be 0 if orphan_transactions = true.
	AffectedTransactions *uint32
	// The # of transactions that have subsequently been "picked up" by other mappings
	RemappedTransactions *uint32
}

func (b0 RespDelete_builder) Build() *RespDelete {
	m0 := &RespDelete{}
	b, x := &b0, m0
	_, _ = b, x
	if b.AffectedTransactions != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_AffectedTransactions = *b.AffectedTransactions
	}
	if b.RemappedTransactions != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_RemappedTransactions = *b.RemappedTransactions
	}
	return m0
}

var File_bank_data_mappings_proto protoreflect.FileDescriptor

const file_bank_data_mappings_proto_rawDesc = "" +
	"\n" +
	"\x18bank_data/mappings.proto\x12\bmappings\"j\n" +
	"\aReqList\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\rR\bpageSize\x12)\n" +
	"\x10pagination_token\x18\x02 \x01(\tR\x0fpaginationToken\x12\x17\n" +
	"\acard_id\x18\x03 \x01(\tR\x06cardId\"\x81\x01\n" +
	"\bRespList\x12\x1f\n" +
	"\vtotal_count\x18\x01 \x01(\rR\n" +
	"totalCount\x12)\n" +
	"\x10pagination_token\x18\x02 \x01(\tR\x0fpaginationToken\x12)\n" +
	"\x06result\x18\x03 \x03(\v2\x11.mappings.MappingR\x06result\"\xba\x02\n" +
	"\x06ReqNew\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12,\n" +
	"\x12result_category_id\x18\x03 \x01(\tR\x10resultCategoryId\x12\x1f\n" +
	"\vresult_name\x18\x04 \x01(\tR\n" +
	"resultName\x12\x1d\n" +
	"\n" +
	"match_text\x18\x05 \x01(\tR\tmatchText\x12E\n" +
	"\x11match_amount_mode\x18\x06 \x01(\x0e2\x19.mappings.AmountMatchModeR\x0fmatchAmountMode\x12!\n" +
	"\fmatch_amount\x18\a \x01(\x01R\vmatchAmount\x12\"\n" +
	"\rmatch_card_id\x18\b \x01(\tR\vmatchCardId\x12\x1a\n" +
	"\bpriority\x18\t \x01(\x05R\bpriorityJ\x04\b\x01\x10\x02\"\x9a\x01\n" +
	"\aRespNew\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12/\n" +
	"\x13mapped_transactions\x18\x02 \x01(\rR\x12mappedTransactions\x12!\n" +
	"\fmapped_names\x18\x03 \x01(\rR\vmappedNames\x12+\n" +
	"\x11mapped_categories\x18\x04 \x01(\rR\x10mappedCategories\"\xc5\x02\n" +
	"\aMapping\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12,\n" +
	"\x12result_category_id\x18\x03 \x01(\tR\x10resultCategoryId\x12\x1f\n" +
	"\vresult_name\x18\x04 \x01(\tR\n" +
	"resultName\x12\x1d\n" +
	"\n" +
	"match_text\x18\x05 \x01(\tR\tmatchText\x12E\n" +
	"\x11match_amount_mode\x18\x06 \x01(\x0e2\x19.mappings.AmountMatchModeR\x0fmatchAmountMode\x12!\n" +
	"\fmatch_amount\x18\a \x01(\x01R\vmatchAmount\x12\"\n" +
	"\rmatch_card_id\x18\b \x01(\tR\vmatchCardId\x12\x1a\n" +
	"\bpriority\x18\t \x01(\x05R\bpriority\"L\n" +
	"\tReqDelete\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12/\n" +
	"\x13orphan_transactions\x18\x02 \x01(\bR\x12orphanTransactions\"v\n" +
	"\n" +
	"RespDelete\x123\n" +
	"\x15affected_transactions\x18\x01 \x01(\rR\x14affectedTransactions\x123\n" +
	"\x15remapped_transactions\x18\x02 \x01(\rR\x14remappedTransactions*>\n" +
	"\x0fAmountMatchMode\x12\t\n" +
	"\x05EXACT\x10\x00\x12\x06\n" +
	"\x02GT\x10\x01\x12\a\n" +
	"\x03GTE\x10\x02\x12\x06\n" +
	"\x02LT\x10\x03\x12\a\n" +
	"\x03LTE\x10\x04B6Z.github.com/shadiestgoat/bankDataDB/pb/mappingsʵ\x03\x02\b\x01b\beditionsp\xe9\az\x0epatch/go.proto"

var file_bank_data_mappings_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_bank_data_mappings_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_bank_data_mappings_proto_goTypes = []any{
	(AmountMatchMode)(0), // 0: mappings.AmountMatchMode
	(*ReqList)(nil),      // 1: mappings.ReqList
	(*RespList)(nil),     // 2: mappings.RespList
	(*ReqNew)(nil),       // 3: mappings.ReqNew
	(*RespNew)(nil),      // 4: mappings.RespNew
	(*Mapping)(nil),      // 5: mappings.Mapping
	(*ReqDelete)(nil),    // 6: mappings.ReqDelete
	(*RespDelete)(nil),   // 7: mappings.RespDelete
}
var file_bank_data_mappings_proto_depIdxs = []int32{
	5, // 0: mappings.RespList.result:type_name -> mappings.Mapping
	0, // 1: mappings.ReqNew.match_amount_mode:type_name -> mappings.AmountMatchMode
	0, // 2: mappings.Mapping.match_amount_mode:type_name -> mappings.AmountMatchMode
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_bank_data_mappings_proto_init() }
func file_bank_data_mappings_proto_init() {
	if File_bank_data_mappings_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bank_data_mappings_proto_rawDesc), len(file_bank_data_mappings_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_bank_data_mappings_proto_goTypes,
		DependencyIndexes: file_bank_data_mappings_proto_depIdxs,
		EnumInfos:         file_bank_data_mappings_proto_enumTypes,
		MessageInfos:      file_bank_data_mappings_proto_msgTypes,
	}.Build()
	File_bank_data_mappings_proto = out.File
	file_bank_data_mappings_proto_goTypes = nil
	file_bank_data_mappings_proto_depIdxs = nil
}
