// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: transactions.sql

package store

import (
	"context"
	"time"

	"github.com/shopspring/decimal"
)

type MappedTransactionsInsertParams struct {
	TransID     string `json:"transId"`
	MappingID   string `json:"mappingId"`
	UpdatedName bool   `json:"updatedName"`
}

const transactionsExists = `-- name: TransactionsExists :one
SELECT EXISTS(
    SELECT 1 FROM transactions WHERE card_id = $1 AND authed_at = $2 AND settled_at = $3 AND description = $4 AND amount = $5
)
`

func (q *DBStore) TransactionsExists(ctx context.Context, cardID string, authedAt time.Time, settledAt time.Time, description string, amount decimal.Decimal) (bool, error) {
	row := q.db.QueryRow(ctx, transactionsExists,
		cardID,
		authedAt,
		settledAt,
		description,
		amount,
	)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

type TransactionsInsertParams struct {
	ID               string          `json:"id"`
	AuthorID         string          `json:"authorId"`
	CardID           string          `json:"cardId"`
	AuthedAt         time.Time       `json:"authedAt"`
	SettledAt        time.Time       `json:"settledAt"`
	Description      string          `json:"description"`
	Amount           decimal.Decimal `json:"amount"`
	ResolvedName     *string         `json:"resolvedName"`
	ResolvedCategory *string         `json:"resolvedCategory"`
}
