// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: auth.sql

package store

import (
	"context"
	"time"
)

const userByName = `-- name: UserByName :one
SELECT id, password FROM users WHERE username = $1
`

type UserByNameRow struct {
	ID       string `json:"id"`
	Password string `json:"password"`
}

func (q *DBStore) UserByName(ctx context.Context, username string) (*UserByNameRow, error) {
	row := q.db.QueryRow(ctx, userByName, username)
	var i UserByNameRow
	err := row.Scan(&i.ID, &i.Password)
	return &i, err
}

const userUpdatedAt = `-- name: UserUpdatedAt :one
SELECT updated_at FROM users WHERE id = $1
`

func (q *DBStore) UserUpdatedAt(ctx context.Context, id string) (time.Time, error) {
	row := q.db.QueryRow(ctx, userUpdatedAt, id)
	var updated_at time.Time
	err := row.Scan(&updated_at)
	return updated_at, err
}
