// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: mappings.sql

package store

import (
	"context"

	"github.com/shopspring/decimal"
)

const mappingsDeleteForCategoryDelete = `-- name: MappingsDeleteForCategoryDelete :exec
DELETE FROM mappings WHERE res_category = $1 AND res_name IS NULL
`

func (q *DBStore) MappingsDeleteForCategoryDelete(ctx context.Context, resCategory *string) error {
	_, err := q.db.Exec(ctx, mappingsDeleteForCategoryDelete, resCategory)
	return err
}

const mappingsDeleteKeepingOrphans = `-- name: MappingsDeleteKeepingOrphans :execrows
DELETE FROM mappings WHERE author_id = $1 AND id = $2
`

func (q *DBStore) MappingsDeleteKeepingOrphans(ctx context.Context, authorID string, iD string) (int64, error) {
	result, err := q.db.Exec(ctx, mappingsDeleteKeepingOrphans, authorID, iD)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const mappingsDeleteNoOrphans = `-- name: MappingsDeleteNoOrphans :many
WITH deleted AS (
    -- run the deletion
    DELETE FROM mapped_transactions
    WHERE mapping_id = 'mapping'
    RETURNING trans_id, updated_name
), flattened AS (
    -- flatten the fuckers into a single 'trans_id', 'did i update the name' 'did i update the category' table
    -- we COULD run a complex delete function here, but 
    SELECT
        trans_id,
        BOOL_OR(updated_name IS TRUE) AS up_name,
        BOOL_OR(updated_name IS FALSE) AS up_cat
    FROM deleted
    GROUP BY trans_id
)
SELECT t.id, card_id, description, amount, up_name, up_cat FROM transactions t JOIN flattened ON t.id = trans_id
`

type MappingsDeleteNoOrphansRow struct {
	ID          string          `json:"id"`
	CardID      string          `json:"cardId"`
	Description string          `json:"description"`
	Amount      decimal.Decimal `json:"amount"`
	UpName      bool            `json:"upName"`
	UpCat       bool            `json:"upCat"`
}

func (q *DBStore) MappingsDeleteNoOrphans(ctx context.Context) ([]*MappingsDeleteNoOrphansRow, error) {
	rows, err := q.db.Query(ctx, mappingsDeleteNoOrphans)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*MappingsDeleteNoOrphansRow
	for rows.Next() {
		var i MappingsDeleteNoOrphansRow
		if err := rows.Scan(
			&i.ID,
			&i.CardID,
			&i.Description,
			&i.Amount,
			&i.UpName,
			&i.UpCat,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const mappingsExists = `-- name: MappingsExists :one
SELECT EXISTS(SELECT 1 FROM mappings WHERE author_id = $1 AND id = $2)
`

func (q *DBStore) MappingsExists(ctx context.Context, authorID string, iD string) (bool, error) {
	row := q.db.QueryRow(ctx, mappingsExists, authorID, iD)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const mappingsRemapExistingCategoryID = `-- name: MappingsRemapExistingCategoryID :exec
UPDATE transactions SET resolved_category = $2 WHERE id = (
    SELECT trans_id FROM mapped_transactions
    WHERE mapping_id = $1 AND updated_name IS FALSE
)
`

func (q *DBStore) MappingsRemapExistingCategoryID(ctx context.Context, mappingID string, resolvedCategory *string) error {
	_, err := q.db.Exec(ctx, mappingsRemapExistingCategoryID, mappingID, resolvedCategory)
	return err
}

const mappingsRemapExistingName = `-- name: MappingsRemapExistingName :exec
UPDATE transactions SET resolved_name = $2 WHERE id = (
    SELECT trans_id FROM mapped_transactions
    WHERE mapping_id = $1 AND updated_name IS TRUE
)
`

func (q *DBStore) MappingsRemapExistingName(ctx context.Context, mappingID string, resolvedName *string) error {
	_, err := q.db.Exec(ctx, mappingsRemapExistingName, mappingID, resolvedName)
	return err
}

const mappingsTransactionCount = `-- name: MappingsTransactionCount :one
SELECT COUNT(DISTINCT transaction_id) FROM mapped_transactions WHERE mapping_id = $1
`

func (q *DBStore) MappingsTransactionCount(ctx context.Context, mappingID string) (int64, error) {
	row := q.db.QueryRow(ctx, mappingsTransactionCount, mappingID)
	var count int64
	err := row.Scan(&count)
	return count, err
}
