// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: mappings.sql

package store

import (
	"context"

	"github.com/shopspring/decimal"
)

const mappingsDeleteKeepingOrphans = `-- name: MappingsDeleteKeepingOrphans :execrows
DELETE FROM mappings WHERE author_id = $1 AND id = $2
`

func (q *DBStore) MappingsDeleteKeepingOrphans(ctx context.Context, authorID string, iD string) (int64, error) {
	result, err := q.db.Exec(ctx, mappingsDeleteKeepingOrphans, authorID, iD)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const mappingsDeleteNoOrphans = `-- name: MappingsDeleteNoOrphans :many
WITH deleted AS (
    -- run the deletion
    DELETE FROM mapped_transactions
    WHERE mapping_id = 'mapping'
    RETURNING trans_id, updated_name
), flattened AS (
    -- flatten the fuckers into a single 'trans_id', 'did i update the name' 'did i update the category' table
    -- we COULD run a complex delete function here, but 
    SELECT
        trans_id,
        BOOL_OR(updated_name IS TRUE) AS up_name,
        BOOL_OR(updated_name IS FALSE) AS up_cat
    FROM deleted
    GROUP BY trans_id
)
SELECT t.id, card_id, description, amount, up_name, up_cat FROM transactions t JOIN flattened ON t.id = trans_id
`

type MappingsDeleteNoOrphansRow struct {
	ID          string          `json:"id"`
	CardID      string          `json:"cardId"`
	Description string          `json:"description"`
	Amount      decimal.Decimal `json:"amount"`
	UpName      bool            `json:"upName"`
	UpCat       bool            `json:"upCat"`
}

func (q *DBStore) MappingsDeleteNoOrphans(ctx context.Context) ([]*MappingsDeleteNoOrphansRow, error) {
	rows, err := q.db.Query(ctx, mappingsDeleteNoOrphans)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*MappingsDeleteNoOrphansRow
	for rows.Next() {
		var i MappingsDeleteNoOrphansRow
		if err := rows.Scan(
			&i.ID,
			&i.CardID,
			&i.Description,
			&i.Amount,
			&i.UpName,
			&i.UpCat,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const mappingsExists = `-- name: MappingsExists :one
SELECT EXISTS(SELECT 1 FROM mappings WHERE author_id = $1 AND id = $2)
`

func (q *DBStore) MappingsExists(ctx context.Context, authorID string, iD string) (bool, error) {
	row := q.db.QueryRow(ctx, mappingsExists, authorID, iD)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
