// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: grpc.sql

package store

import (
	"context"
)

const cardsDelete = `-- name: CardsDelete :execrows
DELETE FROM cards WHERE user_id = $1 AND id = $2
`

func (q *DBStore) CardsDelete(ctx context.Context, userID string, iD string) (int64, error) {
	result, err := q.db.Exec(ctx, cardsDelete, userID, iD)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const cardsUpdate = `-- name: CardsUpdate :execrows
UPDATE cards SET name = $3 WHERE user_id = $1 AND id = $2
`

func (q *DBStore) CardsUpdate(ctx context.Context, userID string, iD string, name string) (int64, error) {
	result, err := q.db.Exec(ctx, cardsUpdate, userID, iD, name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const categoriesDelete = `-- name: CategoriesDelete :execrows
DELETE FROM categories WHERE author_id = $1 AND id = $2
`

func (q *DBStore) CategoriesDelete(ctx context.Context, authorID string, iD string) (int64, error) {
	result, err := q.db.Exec(ctx, categoriesDelete, authorID, iD)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const categoriesExists = `-- name: CategoriesExists :one
SELECT EXISTS (
    SELECT 1 FROM categories WHERE id = $1 AND author_id = $2
)
`

func (q *DBStore) CategoriesExists(ctx context.Context, iD string, authorID string) (bool, error) {
	row := q.db.QueryRow(ctx, categoriesExists, iD, authorID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const transactionsDelete = `-- name: TransactionsDelete :execrows
DELETE FROM transactions WHERE author_id = $1 AND id = $2
`

func (q *DBStore) TransactionsDelete(ctx context.Context, authorID string, iD string) (int64, error) {
	result, err := q.db.Exec(ctx, transactionsDelete, authorID, iD)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
