// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: copyfrom.go

package store

import (
	"context"
)

// iteratorForMappedTransactionsInsert implements pgx.CopyFromSource.
type iteratorForMappedTransactionsInsert struct {
	rows                 []*MappedTransactionsInsertParams
	skippedFirstNextCall bool
}

func (r *iteratorForMappedTransactionsInsert) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForMappedTransactionsInsert) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].TransID,
		r.rows[0].MappingID,
		r.rows[0].UpdatedName,
	}, nil
}

func (r iteratorForMappedTransactionsInsert) Err() error {
	return nil
}

func (q *DBStore) MappedTransactionsInsert(ctx context.Context, arg []*MappedTransactionsInsertParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"mapped_transactions"}, []string{"trans_id", "mapping_id", "updated_name"}, &iteratorForMappedTransactionsInsert{rows: arg})
}

// iteratorForTransactionsInsert implements pgx.CopyFromSource.
type iteratorForTransactionsInsert struct {
	rows                 []*TransactionsInsertParams
	skippedFirstNextCall bool
}

func (r *iteratorForTransactionsInsert) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForTransactionsInsert) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ID,
		r.rows[0].AuthorID,
		r.rows[0].CardID,
		r.rows[0].AuthedAt,
		r.rows[0].SettledAt,
		r.rows[0].Description,
		r.rows[0].Amount,
		r.rows[0].ResolvedName,
		r.rows[0].ResolvedCategory,
	}, nil
}

func (r iteratorForTransactionsInsert) Err() error {
	return nil
}

func (q *DBStore) TransactionsInsert(ctx context.Context, arg []*TransactionsInsertParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"transactions"}, []string{"id", "author_id", "card_id", "authed_at", "settled_at", "description", "amount", "resolved_name", "resolved_category"}, &iteratorForTransactionsInsert{rows: arg})
}
