// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: bank_data/cards.proto

package cards

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReqList struct {
	state                      protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_PageSize        uint32                 `protobuf:"varint,1,opt,name=page_size,json=pageSize"`
	xxx_hidden_PaginationToken *string                `protobuf:"bytes,2,opt,name=pagination_token,json=paginationToken"`
	XXX_raceDetectHookData     protoimpl.RaceDetectHookData
	XXX_presence               [1]uint32
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *ReqList) Reset() {
	*x = ReqList{}
	mi := &file_bank_data_cards_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqList) ProtoMessage() {}

func (x *ReqList) ProtoReflect() protoreflect.Message {
	mi := &file_bank_data_cards_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ReqList) GetPageSize() uint32 {
	if x != nil {
		return x.xxx_hidden_PageSize
	}
	return 0
}

func (x *ReqList) GetPaginationToken() string {
	if x != nil {
		if x.xxx_hidden_PaginationToken != nil {
			return *x.xxx_hidden_PaginationToken
		}
		return ""
	}
	return ""
}

func (x *ReqList) SetPageSize(v uint32) {
	x.xxx_hidden_PageSize = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *ReqList) SetPaginationToken(v string) {
	x.xxx_hidden_PaginationToken = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *ReqList) HasPageSize() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ReqList) HasPaginationToken() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *ReqList) ClearPageSize() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_PageSize = 0
}

func (x *ReqList) ClearPaginationToken() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_PaginationToken = nil
}

type ReqList_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	PageSize        *uint32
	PaginationToken *string
}

func (b0 ReqList_builder) Build() *ReqList {
	m0 := &ReqList{}
	b, x := &b0, m0
	_, _ = b, x
	if b.PageSize != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_PageSize = *b.PageSize
	}
	if b.PaginationToken != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_PaginationToken = b.PaginationToken
	}
	return m0
}

type RespList struct {
	state                      protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_TotalCount      uint32                 `protobuf:"varint,1,opt,name=total_count,json=totalCount"`
	xxx_hidden_PaginationToken *string                `protobuf:"bytes,2,opt,name=pagination_token,json=paginationToken"`
	xxx_hidden_Result          *[]*Card               `protobuf:"bytes,3,rep,name=result"`
	XXX_raceDetectHookData     protoimpl.RaceDetectHookData
	XXX_presence               [1]uint32
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *RespList) Reset() {
	*x = RespList{}
	mi := &file_bank_data_cards_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespList) ProtoMessage() {}

func (x *RespList) ProtoReflect() protoreflect.Message {
	mi := &file_bank_data_cards_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RespList) GetTotalCount() uint32 {
	if x != nil {
		return x.xxx_hidden_TotalCount
	}
	return 0
}

func (x *RespList) GetPaginationToken() string {
	if x != nil {
		if x.xxx_hidden_PaginationToken != nil {
			return *x.xxx_hidden_PaginationToken
		}
		return ""
	}
	return ""
}

func (x *RespList) GetResult() []*Card {
	if x != nil {
		if x.xxx_hidden_Result != nil {
			return *x.xxx_hidden_Result
		}
	}
	return nil
}

func (x *RespList) SetTotalCount(v uint32) {
	x.xxx_hidden_TotalCount = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *RespList) SetPaginationToken(v string) {
	x.xxx_hidden_PaginationToken = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *RespList) SetResult(v []*Card) {
	x.xxx_hidden_Result = &v
}

func (x *RespList) HasTotalCount() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *RespList) HasPaginationToken() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *RespList) ClearTotalCount() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_TotalCount = 0
}

func (x *RespList) ClearPaginationToken() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_PaginationToken = nil
}

type RespList_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	TotalCount      *uint32
	PaginationToken *string
	Result          []*Card
}

func (b0 RespList_builder) Build() *RespList {
	m0 := &RespList{}
	b, x := &b0, m0
	_, _ = b, x
	if b.TotalCount != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_TotalCount = *b.TotalCount
	}
	if b.PaginationToken != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_PaginationToken = b.PaginationToken
	}
	x.xxx_hidden_Result = &b.Result
	return m0
}

// A card is an account of sorts for a specific user
type Card struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          *string                `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_Name        *string                `protobuf:"bytes,2,opt,name=name"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Card) Reset() {
	*x = Card{}
	mi := &file_bank_data_cards_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Card) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Card) ProtoMessage() {}

func (x *Card) ProtoReflect() protoreflect.Message {
	mi := &file_bank_data_cards_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Card) GetID() string {
	if x != nil {
		if x.xxx_hidden_Id != nil {
			return *x.xxx_hidden_Id
		}
		return ""
	}
	return ""
}

func (x *Card) GetName() string {
	if x != nil {
		if x.xxx_hidden_Name != nil {
			return *x.xxx_hidden_Name
		}
		return ""
	}
	return ""
}

func (x *Card) SetId(v string) {
	x.xxx_hidden_Id = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *Card) SetName(v string) {
	x.xxx_hidden_Name = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *Card) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Card) HasName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *Card) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

func (x *Card) ClearName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Name = nil
}

type Card_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The ID of the card
	Id *string
	// The name of the card/account
	Name *string
}

func (b0 Card_builder) Build() *Card {
	m0 := &Card{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Id = b.Id
	}
	if b.Name != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Name = b.Name
	}
	return m0
}

type ReqNew struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Name        *string                `protobuf:"bytes,2,opt,name=name"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ReqNew) Reset() {
	*x = ReqNew{}
	mi := &file_bank_data_cards_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqNew) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqNew) ProtoMessage() {}

func (x *ReqNew) ProtoReflect() protoreflect.Message {
	mi := &file_bank_data_cards_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ReqNew) GetName() string {
	if x != nil {
		if x.xxx_hidden_Name != nil {
			return *x.xxx_hidden_Name
		}
		return ""
	}
	return ""
}

func (x *ReqNew) SetName(v string) {
	x.xxx_hidden_Name = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *ReqNew) HasName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ReqNew) ClearName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Name = nil
}

type ReqNew_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The name of the card/account
	Name *string
}

func (b0 ReqNew_builder) Build() *ReqNew {
	m0 := &ReqNew{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Name != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Name = b.Name
	}
	return m0
}

var File_bank_data_cards_proto protoreflect.FileDescriptor

const file_bank_data_cards_proto_rawDesc = "" +
	"\n" +
	"\x15bank_data/cards.proto\x12\x05cards\"Q\n" +
	"\aReqList\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\rR\bpageSize\x12)\n" +
	"\x10pagination_token\x18\x02 \x01(\tR\x0fpaginationToken\"{\n" +
	"\bRespList\x12\x1f\n" +
	"\vtotal_count\x18\x01 \x01(\rR\n" +
	"totalCount\x12)\n" +
	"\x10pagination_token\x18\x02 \x01(\tR\x0fpaginationToken\x12#\n" +
	"\x06result\x18\x03 \x03(\v2\v.cards.CardR\x06result\"*\n" +
	"\x04Card\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\"\n" +
	"\x06ReqNew\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04nameJ\x04\b\x01\x10\x02B3Z+github.com/shadiestgoat/bankDataDB/pb/cardsʵ\x03\x02\b\x01b\beditionsp\xe9\az\x0epatch/go.proto"

var file_bank_data_cards_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_bank_data_cards_proto_goTypes = []any{
	(*ReqList)(nil),  // 0: cards.ReqList
	(*RespList)(nil), // 1: cards.RespList
	(*Card)(nil),     // 2: cards.Card
	(*ReqNew)(nil),   // 3: cards.ReqNew
}
var file_bank_data_cards_proto_depIdxs = []int32{
	2, // 0: cards.RespList.result:type_name -> cards.Card
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_bank_data_cards_proto_init() }
func file_bank_data_cards_proto_init() {
	if File_bank_data_cards_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bank_data_cards_proto_rawDesc), len(file_bank_data_cards_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_bank_data_cards_proto_goTypes,
		DependencyIndexes: file_bank_data_cards_proto_depIdxs,
		MessageInfos:      file_bank_data_cards_proto_msgTypes,
	}.Build()
	File_bank_data_cards_proto = out.File
	file_bank_data_cards_proto_goTypes = nil
	file_bank_data_cards_proto_depIdxs = nil
}
