// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: bank_data/transactions.proto

package transactions

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrderField int32

const (
	OrderFieldAuthedAt  OrderField = 0
	OrderFieldSettledAt OrderField = 1
	OrderFieldAmount    OrderField = 2
)

// Enum value maps for OrderField.
var (
	OrderField_name = map[int32]string{
		0: "AUTHED_AT",
		1: "SETTLED_AT",
		2: "AMOUNT",
	}
	OrderField_value = map[string]int32{
		"AUTHED_AT":  0,
		"SETTLED_AT": 1,
		"AMOUNT":     2,
	}
)

func (x OrderField) Enum() *OrderField {
	p := new(OrderField)
	*p = x
	return p
}

func (x OrderField) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderField) Descriptor() protoreflect.EnumDescriptor {
	return file_bank_data_transactions_proto_enumTypes[0].Descriptor()
}

func (OrderField) Type() protoreflect.EnumType {
	return &file_bank_data_transactions_proto_enumTypes[0]
}

func (x OrderField) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type ReqList struct {
	state                      protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_PageSize        uint32                 `protobuf:"varint,1,opt,name=page_size,json=pageSize"`
	xxx_hidden_PaginationToken *string                `protobuf:"bytes,2,opt,name=pagination_token,json=paginationToken"`
	xxx_hidden_OrderBy         OrderField             `protobuf:"varint,3,opt,name=order_by,json=orderBy,enum=transactions.OrderField"`
	xxx_hidden_Descending      bool                   `protobuf:"varint,4,opt,name=descending"`
	xxx_hidden_CardId          *string                `protobuf:"bytes,5,opt,name=card_id,json=cardId"`
	XXX_raceDetectHookData     protoimpl.RaceDetectHookData
	XXX_presence               [1]uint32
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *ReqList) Reset() {
	*x = ReqList{}
	mi := &file_bank_data_transactions_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqList) ProtoMessage() {}

func (x *ReqList) ProtoReflect() protoreflect.Message {
	mi := &file_bank_data_transactions_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ReqList) GetPageSize() uint32 {
	if x != nil {
		return x.xxx_hidden_PageSize
	}
	return 0
}

func (x *ReqList) GetPaginationToken() string {
	if x != nil {
		if x.xxx_hidden_PaginationToken != nil {
			return *x.xxx_hidden_PaginationToken
		}
		return ""
	}
	return ""
}

func (x *ReqList) GetOrderBy() OrderField {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 2) {
			return x.xxx_hidden_OrderBy
		}
	}
	return OrderFieldAuthedAt
}

func (x *ReqList) GetDescending() bool {
	if x != nil {
		return x.xxx_hidden_Descending
	}
	return false
}

func (x *ReqList) GetCardID() string {
	if x != nil {
		if x.xxx_hidden_CardId != nil {
			return *x.xxx_hidden_CardId
		}
		return ""
	}
	return ""
}

func (x *ReqList) SetPageSize(v uint32) {
	x.xxx_hidden_PageSize = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 5)
}

func (x *ReqList) SetPaginationToken(v string) {
	x.xxx_hidden_PaginationToken = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 5)
}

func (x *ReqList) SetOrderBy(v OrderField) {
	x.xxx_hidden_OrderBy = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 5)
}

func (x *ReqList) SetDescending(v bool) {
	x.xxx_hidden_Descending = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 5)
}

func (x *ReqList) SetCardId(v string) {
	x.xxx_hidden_CardId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 5)
}

func (x *ReqList) HasPageSize() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ReqList) HasPaginationToken() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *ReqList) HasOrderBy() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *ReqList) HasDescending() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *ReqList) HasCardId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *ReqList) ClearPageSize() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_PageSize = 0
}

func (x *ReqList) ClearPaginationToken() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_PaginationToken = nil
}

func (x *ReqList) ClearOrderBy() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_OrderBy = OrderFieldAuthedAt
}

func (x *ReqList) ClearDescending() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Descending = false
}

func (x *ReqList) ClearCardId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_CardId = nil
}

type ReqList_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	PageSize        *uint32
	PaginationToken *string
	OrderBy         *OrderField
	Descending      *bool
	// Filter by card id
	CardId *string
}

func (b0 ReqList_builder) Build() *ReqList {
	m0 := &ReqList{}
	b, x := &b0, m0
	_, _ = b, x
	if b.PageSize != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 5)
		x.xxx_hidden_PageSize = *b.PageSize
	}
	if b.PaginationToken != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 5)
		x.xxx_hidden_PaginationToken = b.PaginationToken
	}
	if b.OrderBy != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 5)
		x.xxx_hidden_OrderBy = *b.OrderBy
	}
	if b.Descending != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 5)
		x.xxx_hidden_Descending = *b.Descending
	}
	if b.CardId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 5)
		x.xxx_hidden_CardId = b.CardId
	}
	return m0
}

type RespList struct {
	state                      protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_TotalCount      uint32                 `protobuf:"varint,1,opt,name=total_count,json=totalCount"`
	xxx_hidden_PaginationToken *string                `protobuf:"bytes,2,opt,name=pagination_token,json=paginationToken"`
	xxx_hidden_Result          *[]*Transaction        `protobuf:"bytes,3,rep,name=result"`
	XXX_raceDetectHookData     protoimpl.RaceDetectHookData
	XXX_presence               [1]uint32
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *RespList) Reset() {
	*x = RespList{}
	mi := &file_bank_data_transactions_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespList) ProtoMessage() {}

func (x *RespList) ProtoReflect() protoreflect.Message {
	mi := &file_bank_data_transactions_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RespList) GetTotalCount() uint32 {
	if x != nil {
		return x.xxx_hidden_TotalCount
	}
	return 0
}

func (x *RespList) GetPaginationToken() string {
	if x != nil {
		if x.xxx_hidden_PaginationToken != nil {
			return *x.xxx_hidden_PaginationToken
		}
		return ""
	}
	return ""
}

func (x *RespList) GetResult() []*Transaction {
	if x != nil {
		if x.xxx_hidden_Result != nil {
			return *x.xxx_hidden_Result
		}
	}
	return nil
}

func (x *RespList) SetTotalCount(v uint32) {
	x.xxx_hidden_TotalCount = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *RespList) SetPaginationToken(v string) {
	x.xxx_hidden_PaginationToken = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *RespList) SetResult(v []*Transaction) {
	x.xxx_hidden_Result = &v
}

func (x *RespList) HasTotalCount() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *RespList) HasPaginationToken() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *RespList) ClearTotalCount() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_TotalCount = 0
}

func (x *RespList) ClearPaginationToken() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_PaginationToken = nil
}

type RespList_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	TotalCount      *uint32
	PaginationToken *string
	Result          []*Transaction
}

func (b0 RespList_builder) Build() *RespList {
	m0 := &RespList{}
	b, x := &b0, m0
	_, _ = b, x
	if b.TotalCount != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_TotalCount = *b.TotalCount
	}
	if b.PaginationToken != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_PaginationToken = b.PaginationToken
	}
	x.xxx_hidden_Result = &b.Result
	return m0
}

// A specific transaction
type Transaction struct {
	state                         protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id                 *string                `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_CardId             *string                `protobuf:"bytes,2,opt,name=card_id,json=cardId"`
	xxx_hidden_SettledAt          int64                  `protobuf:"varint,3,opt,name=settled_at,json=settledAt"`
	xxx_hidden_AuthedAt           int64                  `protobuf:"varint,4,opt,name=authed_at,json=authedAt"`
	xxx_hidden_Description        *string                `protobuf:"bytes,5,opt,name=description"`
	xxx_hidden_Amount             float64                `protobuf:"fixed64,6,opt,name=amount"`
	xxx_hidden_ResolvedName       *string                `protobuf:"bytes,7,opt,name=resolved_name,json=resolvedName"`
	xxx_hidden_ResolvedCategoryId *string                `protobuf:"bytes,8,opt,name=resolved_category_id,json=resolvedCategoryId"`
	XXX_raceDetectHookData        protoimpl.RaceDetectHookData
	XXX_presence                  [1]uint32
	unknownFields                 protoimpl.UnknownFields
	sizeCache                     protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_bank_data_transactions_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_bank_data_transactions_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Transaction) GetID() string {
	if x != nil {
		if x.xxx_hidden_Id != nil {
			return *x.xxx_hidden_Id
		}
		return ""
	}
	return ""
}

func (x *Transaction) GetCardID() string {
	if x != nil {
		if x.xxx_hidden_CardId != nil {
			return *x.xxx_hidden_CardId
		}
		return ""
	}
	return ""
}

func (x *Transaction) GetSettledAt() int64 {
	if x != nil {
		return x.xxx_hidden_SettledAt
	}
	return 0
}

func (x *Transaction) GetAuthedAt() int64 {
	if x != nil {
		return x.xxx_hidden_AuthedAt
	}
	return 0
}

func (x *Transaction) GetDescription() string {
	if x != nil {
		if x.xxx_hidden_Description != nil {
			return *x.xxx_hidden_Description
		}
		return ""
	}
	return ""
}

func (x *Transaction) GetAmount() float64 {
	if x != nil {
		return x.xxx_hidden_Amount
	}
	return 0
}

func (x *Transaction) GetResolvedName() string {
	if x != nil {
		if x.xxx_hidden_ResolvedName != nil {
			return *x.xxx_hidden_ResolvedName
		}
		return ""
	}
	return ""
}

func (x *Transaction) GetResolvedCategoryID() string {
	if x != nil {
		if x.xxx_hidden_ResolvedCategoryId != nil {
			return *x.xxx_hidden_ResolvedCategoryId
		}
		return ""
	}
	return ""
}

func (x *Transaction) SetId(v string) {
	x.xxx_hidden_Id = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 8)
}

func (x *Transaction) SetCardId(v string) {
	x.xxx_hidden_CardId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 8)
}

func (x *Transaction) SetSettledAt(v int64) {
	x.xxx_hidden_SettledAt = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 8)
}

func (x *Transaction) SetAuthedAt(v int64) {
	x.xxx_hidden_AuthedAt = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 8)
}

func (x *Transaction) SetDescription(v string) {
	x.xxx_hidden_Description = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 8)
}

func (x *Transaction) SetAmount(v float64) {
	x.xxx_hidden_Amount = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 8)
}

func (x *Transaction) SetResolvedName(v string) {
	x.xxx_hidden_ResolvedName = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 6, 8)
}

func (x *Transaction) SetResolvedCategoryId(v string) {
	x.xxx_hidden_ResolvedCategoryId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 7, 8)
}

func (x *Transaction) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Transaction) HasCardId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *Transaction) HasSettledAt() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *Transaction) HasAuthedAt() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *Transaction) HasDescription() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *Transaction) HasAmount() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *Transaction) HasResolvedName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 6)
}

func (x *Transaction) HasResolvedCategoryId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 7)
}

func (x *Transaction) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

func (x *Transaction) ClearCardId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_CardId = nil
}

func (x *Transaction) ClearSettledAt() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_SettledAt = 0
}

func (x *Transaction) ClearAuthedAt() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_AuthedAt = 0
}

func (x *Transaction) ClearDescription() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_Description = nil
}

func (x *Transaction) ClearAmount() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_Amount = 0
}

func (x *Transaction) ClearResolvedName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 6)
	x.xxx_hidden_ResolvedName = nil
}

func (x *Transaction) ClearResolvedCategoryId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 7)
	x.xxx_hidden_ResolvedCategoryId = nil
}

type Transaction_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// ID of the transaction
	Id *string
	// The card this transaction is on
	CardId *string
	// The time the transaction was settled at (unix milliseconds)
	SettledAt *int64
	// The time the transaction was authed at (unix milliseconds)
	AuthedAt *int64
	// Bank's description of the transaction
	Description *string
	// The amount in the transaction
	Amount *float64
	// The actual name of this transaction. Might be not present.
	ResolvedName *string
	// The category of this transaction. Might be not present.
	ResolvedCategoryId *string
}

func (b0 Transaction_builder) Build() *Transaction {
	m0 := &Transaction{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 8)
		x.xxx_hidden_Id = b.Id
	}
	if b.CardId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 8)
		x.xxx_hidden_CardId = b.CardId
	}
	if b.SettledAt != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 8)
		x.xxx_hidden_SettledAt = *b.SettledAt
	}
	if b.AuthedAt != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 8)
		x.xxx_hidden_AuthedAt = *b.AuthedAt
	}
	if b.Description != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 8)
		x.xxx_hidden_Description = b.Description
	}
	if b.Amount != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 8)
		x.xxx_hidden_Amount = *b.Amount
	}
	if b.ResolvedName != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 6, 8)
		x.xxx_hidden_ResolvedName = b.ResolvedName
	}
	if b.ResolvedCategoryId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 7, 8)
		x.xxx_hidden_ResolvedCategoryId = b.ResolvedCategoryId
	}
	return m0
}

// A specific transaction
type ReqNew struct {
	state                         protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_CardId             *string                `protobuf:"bytes,2,opt,name=card_id,json=cardId"`
	xxx_hidden_SettledAt          int64                  `protobuf:"varint,3,opt,name=settled_at,json=settledAt"`
	xxx_hidden_AuthedAt           int64                  `protobuf:"varint,4,opt,name=authed_at,json=authedAt"`
	xxx_hidden_Description        *string                `protobuf:"bytes,5,opt,name=description"`
	xxx_hidden_Amount             float64                `protobuf:"fixed64,6,opt,name=amount"`
	xxx_hidden_ResolvedName       *string                `protobuf:"bytes,7,opt,name=resolved_name,json=resolvedName"`
	xxx_hidden_ResolvedCategoryId *string                `protobuf:"bytes,8,opt,name=resolved_category_id,json=resolvedCategoryId"`
	xxx_hidden_DoNotResolve       bool                   `protobuf:"varint,9,opt,name=do_not_resolve,json=doNotResolve"`
	XXX_raceDetectHookData        protoimpl.RaceDetectHookData
	XXX_presence                  [1]uint32
	unknownFields                 protoimpl.UnknownFields
	sizeCache                     protoimpl.SizeCache
}

func (x *ReqNew) Reset() {
	*x = ReqNew{}
	mi := &file_bank_data_transactions_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqNew) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqNew) ProtoMessage() {}

func (x *ReqNew) ProtoReflect() protoreflect.Message {
	mi := &file_bank_data_transactions_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ReqNew) GetCardID() string {
	if x != nil {
		if x.xxx_hidden_CardId != nil {
			return *x.xxx_hidden_CardId
		}
		return ""
	}
	return ""
}

func (x *ReqNew) GetSettledAt() int64 {
	if x != nil {
		return x.xxx_hidden_SettledAt
	}
	return 0
}

func (x *ReqNew) GetAuthedAt() int64 {
	if x != nil {
		return x.xxx_hidden_AuthedAt
	}
	return 0
}

func (x *ReqNew) GetDescription() string {
	if x != nil {
		if x.xxx_hidden_Description != nil {
			return *x.xxx_hidden_Description
		}
		return ""
	}
	return ""
}

func (x *ReqNew) GetAmount() float64 {
	if x != nil {
		return x.xxx_hidden_Amount
	}
	return 0
}

func (x *ReqNew) GetResolvedName() string {
	if x != nil {
		if x.xxx_hidden_ResolvedName != nil {
			return *x.xxx_hidden_ResolvedName
		}
		return ""
	}
	return ""
}

func (x *ReqNew) GetResolvedCategoryID() string {
	if x != nil {
		if x.xxx_hidden_ResolvedCategoryId != nil {
			return *x.xxx_hidden_ResolvedCategoryId
		}
		return ""
	}
	return ""
}

func (x *ReqNew) GetDoNotResolve() bool {
	if x != nil {
		return x.xxx_hidden_DoNotResolve
	}
	return false
}

func (x *ReqNew) SetCardId(v string) {
	x.xxx_hidden_CardId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 8)
}

func (x *ReqNew) SetSettledAt(v int64) {
	x.xxx_hidden_SettledAt = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 8)
}

func (x *ReqNew) SetAuthedAt(v int64) {
	x.xxx_hidden_AuthedAt = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 8)
}

func (x *ReqNew) SetDescription(v string) {
	x.xxx_hidden_Description = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 8)
}

func (x *ReqNew) SetAmount(v float64) {
	x.xxx_hidden_Amount = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 8)
}

func (x *ReqNew) SetResolvedName(v string) {
	x.xxx_hidden_ResolvedName = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 8)
}

func (x *ReqNew) SetResolvedCategoryId(v string) {
	x.xxx_hidden_ResolvedCategoryId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 6, 8)
}

func (x *ReqNew) SetDoNotResolve(v bool) {
	x.xxx_hidden_DoNotResolve = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 7, 8)
}

func (x *ReqNew) HasCardId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ReqNew) HasSettledAt() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *ReqNew) HasAuthedAt() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *ReqNew) HasDescription() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *ReqNew) HasAmount() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *ReqNew) HasResolvedName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *ReqNew) HasResolvedCategoryId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 6)
}

func (x *ReqNew) HasDoNotResolve() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 7)
}

func (x *ReqNew) ClearCardId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_CardId = nil
}

func (x *ReqNew) ClearSettledAt() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_SettledAt = 0
}

func (x *ReqNew) ClearAuthedAt() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_AuthedAt = 0
}

func (x *ReqNew) ClearDescription() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Description = nil
}

func (x *ReqNew) ClearAmount() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_Amount = 0
}

func (x *ReqNew) ClearResolvedName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_ResolvedName = nil
}

func (x *ReqNew) ClearResolvedCategoryId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 6)
	x.xxx_hidden_ResolvedCategoryId = nil
}

func (x *ReqNew) ClearDoNotResolve() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 7)
	x.xxx_hidden_DoNotResolve = false
}

type ReqNew_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The card this transaction is on
	CardId *string
	// The time the transaction was settled at (unix milliseconds)
	SettledAt *int64
	// The time the transaction was authed at (unix milliseconds)
	AuthedAt *int64
	// Bank's description of the transaction
	Description *string
	// The amount in the transaction
	Amount *float64
	// The actual name of this transaction. Might be not present.
	ResolvedName *string
	// The category of this transaction. Might be not present.
	ResolvedCategoryId *string
	// If true, will not attempt to resolve this transaction this time
	DoNotResolve *bool
}

func (b0 ReqNew_builder) Build() *ReqNew {
	m0 := &ReqNew{}
	b, x := &b0, m0
	_, _ = b, x
	if b.CardId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 8)
		x.xxx_hidden_CardId = b.CardId
	}
	if b.SettledAt != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 8)
		x.xxx_hidden_SettledAt = *b.SettledAt
	}
	if b.AuthedAt != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 8)
		x.xxx_hidden_AuthedAt = *b.AuthedAt
	}
	if b.Description != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 8)
		x.xxx_hidden_Description = b.Description
	}
	if b.Amount != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 8)
		x.xxx_hidden_Amount = *b.Amount
	}
	if b.ResolvedName != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 8)
		x.xxx_hidden_ResolvedName = b.ResolvedName
	}
	if b.ResolvedCategoryId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 6, 8)
		x.xxx_hidden_ResolvedCategoryId = b.ResolvedCategoryId
	}
	if b.DoNotResolve != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 7, 8)
		x.xxx_hidden_DoNotResolve = *b.DoNotResolve
	}
	return m0
}

type RespNew struct {
	state                         protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id                 *string                `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_ResolvedName       *string                `protobuf:"bytes,7,opt,name=resolved_name,json=resolvedName"`
	xxx_hidden_ResolvedCategoryId *string                `protobuf:"bytes,8,opt,name=resolved_category_id,json=resolvedCategoryId"`
	XXX_raceDetectHookData        protoimpl.RaceDetectHookData
	XXX_presence                  [1]uint32
	unknownFields                 protoimpl.UnknownFields
	sizeCache                     protoimpl.SizeCache
}

func (x *RespNew) Reset() {
	*x = RespNew{}
	mi := &file_bank_data_transactions_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespNew) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespNew) ProtoMessage() {}

func (x *RespNew) ProtoReflect() protoreflect.Message {
	mi := &file_bank_data_transactions_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RespNew) GetID() string {
	if x != nil {
		if x.xxx_hidden_Id != nil {
			return *x.xxx_hidden_Id
		}
		return ""
	}
	return ""
}

func (x *RespNew) GetResolvedName() string {
	if x != nil {
		if x.xxx_hidden_ResolvedName != nil {
			return *x.xxx_hidden_ResolvedName
		}
		return ""
	}
	return ""
}

func (x *RespNew) GetResolvedCategoryID() string {
	if x != nil {
		if x.xxx_hidden_ResolvedCategoryId != nil {
			return *x.xxx_hidden_ResolvedCategoryId
		}
		return ""
	}
	return ""
}

func (x *RespNew) SetId(v string) {
	x.xxx_hidden_Id = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *RespNew) SetResolvedName(v string) {
	x.xxx_hidden_ResolvedName = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *RespNew) SetResolvedCategoryId(v string) {
	x.xxx_hidden_ResolvedCategoryId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
}

func (x *RespNew) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *RespNew) HasResolvedName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *RespNew) HasResolvedCategoryId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *RespNew) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

func (x *RespNew) ClearResolvedName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_ResolvedName = nil
}

func (x *RespNew) ClearResolvedCategoryId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_ResolvedCategoryId = nil
}

type RespNew_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id                 *string
	ResolvedName       *string
	ResolvedCategoryId *string
}

func (b0 RespNew_builder) Build() *RespNew {
	m0 := &RespNew{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_Id = b.Id
	}
	if b.ResolvedName != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_ResolvedName = b.ResolvedName
	}
	if b.ResolvedCategoryId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_ResolvedCategoryId = b.ResolvedCategoryId
	}
	return m0
}

type ReqUpdate struct {
	state                         protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id                 *string                `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_ResolvedName       *string                `protobuf:"bytes,7,opt,name=resolved_name,json=resolvedName"`
	xxx_hidden_ResolvedCategoryId *string                `protobuf:"bytes,8,opt,name=resolved_category_id,json=resolvedCategoryId"`
	XXX_raceDetectHookData        protoimpl.RaceDetectHookData
	XXX_presence                  [1]uint32
	unknownFields                 protoimpl.UnknownFields
	sizeCache                     protoimpl.SizeCache
}

func (x *ReqUpdate) Reset() {
	*x = ReqUpdate{}
	mi := &file_bank_data_transactions_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqUpdate) ProtoMessage() {}

func (x *ReqUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_bank_data_transactions_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ReqUpdate) GetID() string {
	if x != nil {
		if x.xxx_hidden_Id != nil {
			return *x.xxx_hidden_Id
		}
		return ""
	}
	return ""
}

func (x *ReqUpdate) GetResolvedName() string {
	if x != nil {
		if x.xxx_hidden_ResolvedName != nil {
			return *x.xxx_hidden_ResolvedName
		}
		return ""
	}
	return ""
}

func (x *ReqUpdate) GetResolvedCategoryID() string {
	if x != nil {
		if x.xxx_hidden_ResolvedCategoryId != nil {
			return *x.xxx_hidden_ResolvedCategoryId
		}
		return ""
	}
	return ""
}

func (x *ReqUpdate) SetId(v string) {
	x.xxx_hidden_Id = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *ReqUpdate) SetResolvedName(v string) {
	x.xxx_hidden_ResolvedName = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *ReqUpdate) SetResolvedCategoryId(v string) {
	x.xxx_hidden_ResolvedCategoryId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
}

func (x *ReqUpdate) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ReqUpdate) HasResolvedName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *ReqUpdate) HasResolvedCategoryId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *ReqUpdate) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

func (x *ReqUpdate) ClearResolvedName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_ResolvedName = nil
}

func (x *ReqUpdate) ClearResolvedCategoryId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_ResolvedCategoryId = nil
}

type ReqUpdate_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id                 *string
	ResolvedName       *string
	ResolvedCategoryId *string
}

func (b0 ReqUpdate_builder) Build() *ReqUpdate {
	m0 := &ReqUpdate{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_Id = b.Id
	}
	if b.ResolvedName != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_ResolvedName = b.ResolvedName
	}
	if b.ResolvedCategoryId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_ResolvedCategoryId = b.ResolvedCategoryId
	}
	return m0
}

var File_bank_data_transactions_proto protoreflect.FileDescriptor

const file_bank_data_transactions_proto_rawDesc = "" +
	"\n" +
	"\x1cbank_data/transactions.proto\x12\ftransactions\"\xbf\x01\n" +
	"\aReqList\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\rR\bpageSize\x12)\n" +
	"\x10pagination_token\x18\x02 \x01(\tR\x0fpaginationToken\x123\n" +
	"\border_by\x18\x03 \x01(\x0e2\x18.transactions.OrderFieldR\aorderBy\x12\x1e\n" +
	"\n" +
	"descending\x18\x04 \x01(\bR\n" +
	"descending\x12\x17\n" +
	"\acard_id\x18\x05 \x01(\tR\x06cardId\"\x89\x01\n" +
	"\bRespList\x12\x1f\n" +
	"\vtotal_count\x18\x01 \x01(\rR\n" +
	"totalCount\x12)\n" +
	"\x10pagination_token\x18\x02 \x01(\tR\x0fpaginationToken\x121\n" +
	"\x06result\x18\x03 \x03(\v2\x19.transactions.TransactionR\x06result\"\x83\x02\n" +
	"\vTransaction\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\acard_id\x18\x02 \x01(\tR\x06cardId\x12\x1d\n" +
	"\n" +
	"settled_at\x18\x03 \x01(\x03R\tsettledAt\x12\x1b\n" +
	"\tauthed_at\x18\x04 \x01(\x03R\bauthedAt\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x16\n" +
	"\x06amount\x18\x06 \x01(\x01R\x06amount\x12#\n" +
	"\rresolved_name\x18\a \x01(\tR\fresolvedName\x120\n" +
	"\x14resolved_category_id\x18\b \x01(\tR\x12resolvedCategoryId\"\x9a\x02\n" +
	"\x06ReqNew\x12\x17\n" +
	"\acard_id\x18\x02 \x01(\tR\x06cardId\x12\x1d\n" +
	"\n" +
	"settled_at\x18\x03 \x01(\x03R\tsettledAt\x12\x1b\n" +
	"\tauthed_at\x18\x04 \x01(\x03R\bauthedAt\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x16\n" +
	"\x06amount\x18\x06 \x01(\x01R\x06amount\x12#\n" +
	"\rresolved_name\x18\a \x01(\tR\fresolvedName\x120\n" +
	"\x14resolved_category_id\x18\b \x01(\tR\x12resolvedCategoryId\x12$\n" +
	"\x0edo_not_resolve\x18\t \x01(\bR\fdoNotResolveJ\x04\b\x01\x10\x02\"p\n" +
	"\aRespNew\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12#\n" +
	"\rresolved_name\x18\a \x01(\tR\fresolvedName\x120\n" +
	"\x14resolved_category_id\x18\b \x01(\tR\x12resolvedCategoryId\"r\n" +
	"\tReqUpdate\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12#\n" +
	"\rresolved_name\x18\a \x01(\tR\fresolvedName\x120\n" +
	"\x14resolved_category_id\x18\b \x01(\tR\x12resolvedCategoryId*7\n" +
	"\n" +
	"OrderField\x12\r\n" +
	"\tAUTHED_AT\x10\x00\x12\x0e\n" +
	"\n" +
	"SETTLED_AT\x10\x01\x12\n" +
	"\n" +
	"\x06AMOUNT\x10\x02B:Z2github.com/shadiestgoat/bankDataDB/pb/transactionsʵ\x03\x02\b\x01b\beditionsp\xe9\az\x0epatch/go.proto"

var file_bank_data_transactions_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_bank_data_transactions_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_bank_data_transactions_proto_goTypes = []any{
	(OrderField)(0),     // 0: transactions.OrderField
	(*ReqList)(nil),     // 1: transactions.ReqList
	(*RespList)(nil),    // 2: transactions.RespList
	(*Transaction)(nil), // 3: transactions.Transaction
	(*ReqNew)(nil),      // 4: transactions.ReqNew
	(*RespNew)(nil),     // 5: transactions.RespNew
	(*ReqUpdate)(nil),   // 6: transactions.ReqUpdate
}
var file_bank_data_transactions_proto_depIdxs = []int32{
	0, // 0: transactions.ReqList.order_by:type_name -> transactions.OrderField
	3, // 1: transactions.RespList.result:type_name -> transactions.Transaction
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_bank_data_transactions_proto_init() }
func file_bank_data_transactions_proto_init() {
	if File_bank_data_transactions_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bank_data_transactions_proto_rawDesc), len(file_bank_data_transactions_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_bank_data_transactions_proto_goTypes,
		DependencyIndexes: file_bank_data_transactions_proto_depIdxs,
		EnumInfos:         file_bank_data_transactions_proto_enumTypes,
		MessageInfos:      file_bank_data_transactions_proto_msgTypes,
	}.Build()
	File_bank_data_transactions_proto = out.File
	file_bank_data_transactions_proto_goTypes = nil
	file_bank_data_transactions_proto_depIdxs = nil
}
