// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: bank_data.proto

package bank_svc_pb

import (
	context "context"
	cards "github.com/shadiestgoat/bankDataDB/pb/cards"
	categories "github.com/shadiestgoat/bankDataDB/pb/categories"
	mappings "github.com/shadiestgoat/bankDataDB/pb/mappings"
	transactions "github.com/shadiestgoat/bankDataDB/pb/transactions"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BankData_MappingsList_FullMethodName       = "/main.BankData/MappingsList"
	BankData_MappingsNew_FullMethodName        = "/main.BankData/MappingsNew"
	BankData_MappingsUpdate_FullMethodName     = "/main.BankData/MappingsUpdate"
	BankData_MappingDelete_FullMethodName      = "/main.BankData/MappingDelete"
	BankData_CategoriesList_FullMethodName     = "/main.BankData/CategoriesList"
	BankData_CategoriesNew_FullMethodName      = "/main.BankData/CategoriesNew"
	BankData_CategoriesUpdate_FullMethodName   = "/main.BankData/CategoriesUpdate"
	BankData_CategoriesDelete_FullMethodName   = "/main.BankData/CategoriesDelete"
	BankData_TransactionsList_FullMethodName   = "/main.BankData/TransactionsList"
	BankData_TransactionsNew_FullMethodName    = "/main.BankData/TransactionsNew"
	BankData_TransactionsUpdate_FullMethodName = "/main.BankData/TransactionsUpdate"
	BankData_TransactionsDelete_FullMethodName = "/main.BankData/TransactionsDelete"
	BankData_CardsList_FullMethodName          = "/main.BankData/CardsList"
	BankData_CardsNew_FullMethodName           = "/main.BankData/CardsNew"
	BankData_CardsUpdate_FullMethodName        = "/main.BankData/CardsUpdate"
	BankData_CardDelete_FullMethodName         = "/main.BankData/CardDelete"
	BankData_UploadBankSheet_FullMethodName    = "/main.BankData/UploadBankSheet"
)

// BankDataClient is the client API for BankData service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Bank data GRPC service. Used to interact with data and stuff meow
type BankDataClient interface {
	// List mappings
	MappingsList(ctx context.Context, in *mappings.ReqList, opts ...grpc.CallOption) (*mappings.RespList, error)
	// Create a new mapping
	MappingsNew(ctx context.Context, in *mappings.ReqNew, opts ...grpc.CallOption) (*mappings.RespNew, error)
	// Update an existing mapping, where the existing mapping is gotten through the mapping.id
	MappingsUpdate(ctx context.Context, in *mappings.Mapping, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Delete an existing mapping orphaning or nulling transactions
	MappingDelete(ctx context.Context, in *mappings.ReqDelete, opts ...grpc.CallOption) (*mappings.RespDelete, error)
	// List categories
	CategoriesList(ctx context.Context, in *categories.ReqList, opts ...grpc.CallOption) (*categories.RespList, error)
	// Create a new category
	CategoriesNew(ctx context.Context, in *categories.ReqNew, opts ...grpc.CallOption) (*RespNew, error)
	// Update an existing category, where the existing category is gotten through the category.id
	CategoriesUpdate(ctx context.Context, in *categories.Category, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Delete a category by id
	CategoriesDelete(ctx context.Context, in *ReqDelete, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// List transactions
	TransactionsList(ctx context.Context, in *transactions.ReqList, opts ...grpc.CallOption) (*transactions.RespList, error)
	// Create a transaction ad-hoc. You likely want to use [UploadBankSheet]
	TransactionsNew(ctx context.Context, in *transactions.ReqNew, opts ...grpc.CallOption) (*transactions.RespNew, error)
	// Update a specific transaction (where id is the transaction id)
	TransactionsUpdate(ctx context.Context, in *transactions.ReqUpdate, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Delete a transaction by id
	TransactionsDelete(ctx context.Context, in *ReqDelete, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// List cards
	CardsList(ctx context.Context, in *cards.ReqList, opts ...grpc.CallOption) (*cards.RespList, error)
	// Create a card
	CardsNew(ctx context.Context, in *cards.ReqNew, opts ...grpc.CallOption) (*RespNew, error)
	// Update a specific card, by id
	CardsUpdate(ctx context.Context, in *cards.Card, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Delete a card
	CardDelete(ctx context.Context, in *ReqDelete, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Mass-upload a bank sheet
	UploadBankSheet(ctx context.Context, in *ReqBankSheet, opts ...grpc.CallOption) (*RespBankSheet, error)
}

type bankDataClient struct {
	cc grpc.ClientConnInterface
}

func NewBankDataClient(cc grpc.ClientConnInterface) BankDataClient {
	return &bankDataClient{cc}
}

func (c *bankDataClient) MappingsList(ctx context.Context, in *mappings.ReqList, opts ...grpc.CallOption) (*mappings.RespList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(mappings.RespList)
	err := c.cc.Invoke(ctx, BankData_MappingsList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankDataClient) MappingsNew(ctx context.Context, in *mappings.ReqNew, opts ...grpc.CallOption) (*mappings.RespNew, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(mappings.RespNew)
	err := c.cc.Invoke(ctx, BankData_MappingsNew_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankDataClient) MappingsUpdate(ctx context.Context, in *mappings.Mapping, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, BankData_MappingsUpdate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankDataClient) MappingDelete(ctx context.Context, in *mappings.ReqDelete, opts ...grpc.CallOption) (*mappings.RespDelete, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(mappings.RespDelete)
	err := c.cc.Invoke(ctx, BankData_MappingDelete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankDataClient) CategoriesList(ctx context.Context, in *categories.ReqList, opts ...grpc.CallOption) (*categories.RespList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(categories.RespList)
	err := c.cc.Invoke(ctx, BankData_CategoriesList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankDataClient) CategoriesNew(ctx context.Context, in *categories.ReqNew, opts ...grpc.CallOption) (*RespNew, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RespNew)
	err := c.cc.Invoke(ctx, BankData_CategoriesNew_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankDataClient) CategoriesUpdate(ctx context.Context, in *categories.Category, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, BankData_CategoriesUpdate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankDataClient) CategoriesDelete(ctx context.Context, in *ReqDelete, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, BankData_CategoriesDelete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankDataClient) TransactionsList(ctx context.Context, in *transactions.ReqList, opts ...grpc.CallOption) (*transactions.RespList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(transactions.RespList)
	err := c.cc.Invoke(ctx, BankData_TransactionsList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankDataClient) TransactionsNew(ctx context.Context, in *transactions.ReqNew, opts ...grpc.CallOption) (*transactions.RespNew, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(transactions.RespNew)
	err := c.cc.Invoke(ctx, BankData_TransactionsNew_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankDataClient) TransactionsUpdate(ctx context.Context, in *transactions.ReqUpdate, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, BankData_TransactionsUpdate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankDataClient) TransactionsDelete(ctx context.Context, in *ReqDelete, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, BankData_TransactionsDelete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankDataClient) CardsList(ctx context.Context, in *cards.ReqList, opts ...grpc.CallOption) (*cards.RespList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(cards.RespList)
	err := c.cc.Invoke(ctx, BankData_CardsList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankDataClient) CardsNew(ctx context.Context, in *cards.ReqNew, opts ...grpc.CallOption) (*RespNew, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RespNew)
	err := c.cc.Invoke(ctx, BankData_CardsNew_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankDataClient) CardsUpdate(ctx context.Context, in *cards.Card, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, BankData_CardsUpdate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankDataClient) CardDelete(ctx context.Context, in *ReqDelete, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, BankData_CardDelete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankDataClient) UploadBankSheet(ctx context.Context, in *ReqBankSheet, opts ...grpc.CallOption) (*RespBankSheet, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RespBankSheet)
	err := c.cc.Invoke(ctx, BankData_UploadBankSheet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BankDataServer is the server API for BankData service.
// All implementations must embed UnimplementedBankDataServer
// for forward compatibility.
//
// Bank data GRPC service. Used to interact with data and stuff meow
type BankDataServer interface {
	// List mappings
	MappingsList(context.Context, *mappings.ReqList) (*mappings.RespList, error)
	// Create a new mapping
	MappingsNew(context.Context, *mappings.ReqNew) (*mappings.RespNew, error)
	// Update an existing mapping, where the existing mapping is gotten through the mapping.id
	MappingsUpdate(context.Context, *mappings.Mapping) (*emptypb.Empty, error)
	// Delete an existing mapping orphaning or nulling transactions
	MappingDelete(context.Context, *mappings.ReqDelete) (*mappings.RespDelete, error)
	// List categories
	CategoriesList(context.Context, *categories.ReqList) (*categories.RespList, error)
	// Create a new category
	CategoriesNew(context.Context, *categories.ReqNew) (*RespNew, error)
	// Update an existing category, where the existing category is gotten through the category.id
	CategoriesUpdate(context.Context, *categories.Category) (*emptypb.Empty, error)
	// Delete a category by id
	CategoriesDelete(context.Context, *ReqDelete) (*emptypb.Empty, error)
	// List transactions
	TransactionsList(context.Context, *transactions.ReqList) (*transactions.RespList, error)
	// Create a transaction ad-hoc. You likely want to use [UploadBankSheet]
	TransactionsNew(context.Context, *transactions.ReqNew) (*transactions.RespNew, error)
	// Update a specific transaction (where id is the transaction id)
	TransactionsUpdate(context.Context, *transactions.ReqUpdate) (*emptypb.Empty, error)
	// Delete a transaction by id
	TransactionsDelete(context.Context, *ReqDelete) (*emptypb.Empty, error)
	// List cards
	CardsList(context.Context, *cards.ReqList) (*cards.RespList, error)
	// Create a card
	CardsNew(context.Context, *cards.ReqNew) (*RespNew, error)
	// Update a specific card, by id
	CardsUpdate(context.Context, *cards.Card) (*emptypb.Empty, error)
	// Delete a card
	CardDelete(context.Context, *ReqDelete) (*emptypb.Empty, error)
	// Mass-upload a bank sheet
	UploadBankSheet(context.Context, *ReqBankSheet) (*RespBankSheet, error)
	mustEmbedUnimplementedBankDataServer()
}

// UnimplementedBankDataServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBankDataServer struct{}

func (UnimplementedBankDataServer) MappingsList(context.Context, *mappings.ReqList) (*mappings.RespList, error) {
	return nil, status.Error(codes.Unimplemented, "method MappingsList not implemented")
}
func (UnimplementedBankDataServer) MappingsNew(context.Context, *mappings.ReqNew) (*mappings.RespNew, error) {
	return nil, status.Error(codes.Unimplemented, "method MappingsNew not implemented")
}
func (UnimplementedBankDataServer) MappingsUpdate(context.Context, *mappings.Mapping) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method MappingsUpdate not implemented")
}
func (UnimplementedBankDataServer) MappingDelete(context.Context, *mappings.ReqDelete) (*mappings.RespDelete, error) {
	return nil, status.Error(codes.Unimplemented, "method MappingDelete not implemented")
}
func (UnimplementedBankDataServer) CategoriesList(context.Context, *categories.ReqList) (*categories.RespList, error) {
	return nil, status.Error(codes.Unimplemented, "method CategoriesList not implemented")
}
func (UnimplementedBankDataServer) CategoriesNew(context.Context, *categories.ReqNew) (*RespNew, error) {
	return nil, status.Error(codes.Unimplemented, "method CategoriesNew not implemented")
}
func (UnimplementedBankDataServer) CategoriesUpdate(context.Context, *categories.Category) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method CategoriesUpdate not implemented")
}
func (UnimplementedBankDataServer) CategoriesDelete(context.Context, *ReqDelete) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method CategoriesDelete not implemented")
}
func (UnimplementedBankDataServer) TransactionsList(context.Context, *transactions.ReqList) (*transactions.RespList, error) {
	return nil, status.Error(codes.Unimplemented, "method TransactionsList not implemented")
}
func (UnimplementedBankDataServer) TransactionsNew(context.Context, *transactions.ReqNew) (*transactions.RespNew, error) {
	return nil, status.Error(codes.Unimplemented, "method TransactionsNew not implemented")
}
func (UnimplementedBankDataServer) TransactionsUpdate(context.Context, *transactions.ReqUpdate) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method TransactionsUpdate not implemented")
}
func (UnimplementedBankDataServer) TransactionsDelete(context.Context, *ReqDelete) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method TransactionsDelete not implemented")
}
func (UnimplementedBankDataServer) CardsList(context.Context, *cards.ReqList) (*cards.RespList, error) {
	return nil, status.Error(codes.Unimplemented, "method CardsList not implemented")
}
func (UnimplementedBankDataServer) CardsNew(context.Context, *cards.ReqNew) (*RespNew, error) {
	return nil, status.Error(codes.Unimplemented, "method CardsNew not implemented")
}
func (UnimplementedBankDataServer) CardsUpdate(context.Context, *cards.Card) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method CardsUpdate not implemented")
}
func (UnimplementedBankDataServer) CardDelete(context.Context, *ReqDelete) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method CardDelete not implemented")
}
func (UnimplementedBankDataServer) UploadBankSheet(context.Context, *ReqBankSheet) (*RespBankSheet, error) {
	return nil, status.Error(codes.Unimplemented, "method UploadBankSheet not implemented")
}
func (UnimplementedBankDataServer) mustEmbedUnimplementedBankDataServer() {}
func (UnimplementedBankDataServer) testEmbeddedByValue()                  {}

// UnsafeBankDataServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BankDataServer will
// result in compilation errors.
type UnsafeBankDataServer interface {
	mustEmbedUnimplementedBankDataServer()
}

func RegisterBankDataServer(s grpc.ServiceRegistrar, srv BankDataServer) {
	// If the following call panics, it indicates UnimplementedBankDataServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BankData_ServiceDesc, srv)
}

func _BankData_MappingsList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(mappings.ReqList)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankDataServer).MappingsList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BankData_MappingsList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankDataServer).MappingsList(ctx, req.(*mappings.ReqList))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankData_MappingsNew_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(mappings.ReqNew)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankDataServer).MappingsNew(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BankData_MappingsNew_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankDataServer).MappingsNew(ctx, req.(*mappings.ReqNew))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankData_MappingsUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(mappings.Mapping)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankDataServer).MappingsUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BankData_MappingsUpdate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankDataServer).MappingsUpdate(ctx, req.(*mappings.Mapping))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankData_MappingDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(mappings.ReqDelete)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankDataServer).MappingDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BankData_MappingDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankDataServer).MappingDelete(ctx, req.(*mappings.ReqDelete))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankData_CategoriesList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(categories.ReqList)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankDataServer).CategoriesList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BankData_CategoriesList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankDataServer).CategoriesList(ctx, req.(*categories.ReqList))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankData_CategoriesNew_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(categories.ReqNew)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankDataServer).CategoriesNew(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BankData_CategoriesNew_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankDataServer).CategoriesNew(ctx, req.(*categories.ReqNew))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankData_CategoriesUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(categories.Category)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankDataServer).CategoriesUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BankData_CategoriesUpdate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankDataServer).CategoriesUpdate(ctx, req.(*categories.Category))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankData_CategoriesDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqDelete)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankDataServer).CategoriesDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BankData_CategoriesDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankDataServer).CategoriesDelete(ctx, req.(*ReqDelete))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankData_TransactionsList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(transactions.ReqList)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankDataServer).TransactionsList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BankData_TransactionsList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankDataServer).TransactionsList(ctx, req.(*transactions.ReqList))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankData_TransactionsNew_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(transactions.ReqNew)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankDataServer).TransactionsNew(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BankData_TransactionsNew_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankDataServer).TransactionsNew(ctx, req.(*transactions.ReqNew))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankData_TransactionsUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(transactions.ReqUpdate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankDataServer).TransactionsUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BankData_TransactionsUpdate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankDataServer).TransactionsUpdate(ctx, req.(*transactions.ReqUpdate))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankData_TransactionsDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqDelete)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankDataServer).TransactionsDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BankData_TransactionsDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankDataServer).TransactionsDelete(ctx, req.(*ReqDelete))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankData_CardsList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(cards.ReqList)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankDataServer).CardsList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BankData_CardsList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankDataServer).CardsList(ctx, req.(*cards.ReqList))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankData_CardsNew_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(cards.ReqNew)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankDataServer).CardsNew(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BankData_CardsNew_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankDataServer).CardsNew(ctx, req.(*cards.ReqNew))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankData_CardsUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(cards.Card)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankDataServer).CardsUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BankData_CardsUpdate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankDataServer).CardsUpdate(ctx, req.(*cards.Card))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankData_CardDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqDelete)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankDataServer).CardDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BankData_CardDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankDataServer).CardDelete(ctx, req.(*ReqDelete))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankData_UploadBankSheet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqBankSheet)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankDataServer).UploadBankSheet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BankData_UploadBankSheet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankDataServer).UploadBankSheet(ctx, req.(*ReqBankSheet))
	}
	return interceptor(ctx, in, info, handler)
}

// BankData_ServiceDesc is the grpc.ServiceDesc for BankData service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BankData_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "main.BankData",
	HandlerType: (*BankDataServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MappingsList",
			Handler:    _BankData_MappingsList_Handler,
		},
		{
			MethodName: "MappingsNew",
			Handler:    _BankData_MappingsNew_Handler,
		},
		{
			MethodName: "MappingsUpdate",
			Handler:    _BankData_MappingsUpdate_Handler,
		},
		{
			MethodName: "MappingDelete",
			Handler:    _BankData_MappingDelete_Handler,
		},
		{
			MethodName: "CategoriesList",
			Handler:    _BankData_CategoriesList_Handler,
		},
		{
			MethodName: "CategoriesNew",
			Handler:    _BankData_CategoriesNew_Handler,
		},
		{
			MethodName: "CategoriesUpdate",
			Handler:    _BankData_CategoriesUpdate_Handler,
		},
		{
			MethodName: "CategoriesDelete",
			Handler:    _BankData_CategoriesDelete_Handler,
		},
		{
			MethodName: "TransactionsList",
			Handler:    _BankData_TransactionsList_Handler,
		},
		{
			MethodName: "TransactionsNew",
			Handler:    _BankData_TransactionsNew_Handler,
		},
		{
			MethodName: "TransactionsUpdate",
			Handler:    _BankData_TransactionsUpdate_Handler,
		},
		{
			MethodName: "TransactionsDelete",
			Handler:    _BankData_TransactionsDelete_Handler,
		},
		{
			MethodName: "CardsList",
			Handler:    _BankData_CardsList_Handler,
		},
		{
			MethodName: "CardsNew",
			Handler:    _BankData_CardsNew_Handler,
		},
		{
			MethodName: "CardsUpdate",
			Handler:    _BankData_CardsUpdate_Handler,
		},
		{
			MethodName: "CardDelete",
			Handler:    _BankData_CardDelete_Handler,
		},
		{
			MethodName: "UploadBankSheet",
			Handler:    _BankData_UploadBankSheet_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bank_data.proto",
}
