// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: bank_data.proto

package bank_svc_pb

import (
	cards "github.com/shadiestgoat/bankDataDB/pb/cards"
	categories "github.com/shadiestgoat/bankDataDB/pb/categories"
	mappings "github.com/shadiestgoat/bankDataDB/pb/mappings"
	transactions "github.com/shadiestgoat/bankDataDB/pb/transactions"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RespNew struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          *string                `protobuf:"bytes,1,opt,name=id"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *RespNew) Reset() {
	*x = RespNew{}
	mi := &file_bank_data_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespNew) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespNew) ProtoMessage() {}

func (x *RespNew) ProtoReflect() protoreflect.Message {
	mi := &file_bank_data_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RespNew) GetID() string {
	if x != nil {
		if x.xxx_hidden_Id != nil {
			return *x.xxx_hidden_Id
		}
		return ""
	}
	return ""
}

func (x *RespNew) SetId(v string) {
	x.xxx_hidden_Id = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *RespNew) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *RespNew) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

type RespNew_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// TODO: This might need to become resource specific rather than generic resp new
	Id *string
}

func (b0 RespNew_builder) Build() *RespNew {
	m0 := &RespNew{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Id = b.Id
	}
	return m0
}

type ReqDelete struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          *string                `protobuf:"bytes,1,opt,name=id"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ReqDelete) Reset() {
	*x = ReqDelete{}
	mi := &file_bank_data_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqDelete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqDelete) ProtoMessage() {}

func (x *ReqDelete) ProtoReflect() protoreflect.Message {
	mi := &file_bank_data_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ReqDelete) GetID() string {
	if x != nil {
		if x.xxx_hidden_Id != nil {
			return *x.xxx_hidden_Id
		}
		return ""
	}
	return ""
}

func (x *ReqDelete) SetId(v string) {
	x.xxx_hidden_Id = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *ReqDelete) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ReqDelete) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

type ReqDelete_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id *string
}

func (b0 ReqDelete_builder) Build() *ReqDelete {
	m0 := &ReqDelete{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Id = b.Id
	}
	return m0
}

type ReqBankSheet struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_CardId      *string                `protobuf:"bytes,1,opt,name=card_id,json=cardId"`
	xxx_hidden_BankSheet   *string                `protobuf:"bytes,2,opt,name=bank_sheet,json=bankSheet"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ReqBankSheet) Reset() {
	*x = ReqBankSheet{}
	mi := &file_bank_data_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqBankSheet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqBankSheet) ProtoMessage() {}

func (x *ReqBankSheet) ProtoReflect() protoreflect.Message {
	mi := &file_bank_data_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ReqBankSheet) GetCardID() string {
	if x != nil {
		if x.xxx_hidden_CardId != nil {
			return *x.xxx_hidden_CardId
		}
		return ""
	}
	return ""
}

func (x *ReqBankSheet) GetBankSheet() string {
	if x != nil {
		if x.xxx_hidden_BankSheet != nil {
			return *x.xxx_hidden_BankSheet
		}
		return ""
	}
	return ""
}

func (x *ReqBankSheet) SetCardId(v string) {
	x.xxx_hidden_CardId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *ReqBankSheet) SetBankSheet(v string) {
	x.xxx_hidden_BankSheet = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *ReqBankSheet) HasCardId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ReqBankSheet) HasBankSheet() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *ReqBankSheet) ClearCardId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_CardId = nil
}

func (x *ReqBankSheet) ClearBankSheet() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_BankSheet = nil
}

type ReqBankSheet_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Card id this bank sheet is for
	CardId *string
	// The bank sheet
	BankSheet *string
}

func (b0 ReqBankSheet_builder) Build() *ReqBankSheet {
	m0 := &ReqBankSheet{}
	b, x := &b0, m0
	_, _ = b, x
	if b.CardId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_CardId = b.CardId
	}
	if b.BankSheet != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_BankSheet = b.BankSheet
	}
	return m0
}

type RespBankSheet struct {
	state                            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_NewTransactions       uint64                 `protobuf:"varint,1,opt,name=new_transactions,json=newTransactions"`
	xxx_hidden_DuplicateTransactions uint64                 `protobuf:"varint,2,opt,name=duplicate_transactions,json=duplicateTransactions"`
	xxx_hidden_UnmappedTransactions  uint64                 `protobuf:"varint,3,opt,name=unmapped_transactions,json=unmappedTransactions"`
	XXX_raceDetectHookData           protoimpl.RaceDetectHookData
	XXX_presence                     [1]uint32
	unknownFields                    protoimpl.UnknownFields
	sizeCache                        protoimpl.SizeCache
}

func (x *RespBankSheet) Reset() {
	*x = RespBankSheet{}
	mi := &file_bank_data_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespBankSheet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespBankSheet) ProtoMessage() {}

func (x *RespBankSheet) ProtoReflect() protoreflect.Message {
	mi := &file_bank_data_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RespBankSheet) GetNewTransactions() uint64 {
	if x != nil {
		return x.xxx_hidden_NewTransactions
	}
	return 0
}

func (x *RespBankSheet) GetDuplicateTransactions() uint64 {
	if x != nil {
		return x.xxx_hidden_DuplicateTransactions
	}
	return 0
}

func (x *RespBankSheet) GetUnmappedTransactions() uint64 {
	if x != nil {
		return x.xxx_hidden_UnmappedTransactions
	}
	return 0
}

func (x *RespBankSheet) SetNewTransactions(v uint64) {
	x.xxx_hidden_NewTransactions = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *RespBankSheet) SetDuplicateTransactions(v uint64) {
	x.xxx_hidden_DuplicateTransactions = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *RespBankSheet) SetUnmappedTransactions(v uint64) {
	x.xxx_hidden_UnmappedTransactions = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
}

func (x *RespBankSheet) HasNewTransactions() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *RespBankSheet) HasDuplicateTransactions() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *RespBankSheet) HasUnmappedTransactions() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *RespBankSheet) ClearNewTransactions() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_NewTransactions = 0
}

func (x *RespBankSheet) ClearDuplicateTransactions() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_DuplicateTransactions = 0
}

func (x *RespBankSheet) ClearUnmappedTransactions() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_UnmappedTransactions = 0
}

type RespBankSheet_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	NewTransactions       *uint64
	DuplicateTransactions *uint64
	UnmappedTransactions  *uint64
}

func (b0 RespBankSheet_builder) Build() *RespBankSheet {
	m0 := &RespBankSheet{}
	b, x := &b0, m0
	_, _ = b, x
	if b.NewTransactions != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_NewTransactions = *b.NewTransactions
	}
	if b.DuplicateTransactions != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_DuplicateTransactions = *b.DuplicateTransactions
	}
	if b.UnmappedTransactions != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_UnmappedTransactions = *b.UnmappedTransactions
	}
	return m0
}

var File_bank_data_proto protoreflect.FileDescriptor

const file_bank_data_proto_rawDesc = "" +
	"\n" +
	"\x0fbank_data.proto\x12\x04main\x1a\x18bank_data/mappings.proto\x1a\x1abank_data/categories.proto\x1a\x1cbank_data/transactions.proto\x1a\x15bank_data/cards.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x19\n" +
	"\aRespNew\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x1b\n" +
	"\tReqDelete\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"F\n" +
	"\fReqBankSheet\x12\x17\n" +
	"\acard_id\x18\x01 \x01(\tR\x06cardId\x12\x1d\n" +
	"\n" +
	"bank_sheet\x18\x02 \x01(\tR\tbankSheet\"\xa6\x01\n" +
	"\rRespBankSheet\x12)\n" +
	"\x10new_transactions\x18\x01 \x01(\x04R\x0fnewTransactions\x125\n" +
	"\x16duplicate_transactions\x18\x02 \x01(\x04R\x15duplicateTransactions\x123\n" +
	"\x15unmapped_transactions\x18\x03 \x01(\x04R\x14unmappedTransactions2\xe6\a\n" +
	"\bBankData\x125\n" +
	"\fMappingsList\x12\x11.mappings.ReqList\x1a\x12.mappings.RespList\x122\n" +
	"\vMappingsNew\x12\x10.mappings.ReqNew\x1a\x11.mappings.RespNew\x12;\n" +
	"\x0eMappingsUpdate\x12\x11.mappings.Mapping\x1a\x16.google.protobuf.Empty\x12:\n" +
	"\rMappingDelete\x12\x13.mappings.ReqDelete\x1a\x14.mappings.RespDelete\x12;\n" +
	"\x0eCategoriesList\x12\x13.categories.ReqList\x1a\x14.categories.RespList\x122\n" +
	"\rCategoriesNew\x12\x12.categories.ReqNew\x1a\r.main.RespNew\x12@\n" +
	"\x10CategoriesUpdate\x12\x14.categories.Category\x1a\x16.google.protobuf.Empty\x12;\n" +
	"\x10CategoriesDelete\x12\x0f.main.ReqDelete\x1a\x16.google.protobuf.Empty\x12A\n" +
	"\x10TransactionsList\x12\x15.transactions.ReqList\x1a\x16.transactions.RespList\x12>\n" +
	"\x0fTransactionsNew\x12\x14.transactions.ReqNew\x1a\x15.transactions.RespNew\x12E\n" +
	"\x12TransactionsUpdate\x12\x17.transactions.ReqUpdate\x1a\x16.google.protobuf.Empty\x12=\n" +
	"\x12TransactionsDelete\x12\x0f.main.ReqDelete\x1a\x16.google.protobuf.Empty\x12,\n" +
	"\tCardsList\x12\x0e.cards.ReqList\x1a\x0f.cards.RespList\x12(\n" +
	"\bCardsNew\x12\r.cards.ReqNew\x1a\r.main.RespNew\x122\n" +
	"\vCardsUpdate\x12\v.cards.Card\x1a\x16.google.protobuf.Empty\x125\n" +
	"\n" +
	"CardDelete\x12\x0f.main.ReqDelete\x1a\x16.google.protobuf.Empty\x12:\n" +
	"\x0fUploadBankSheet\x12\x12.main.ReqBankSheet\x1a\x13.main.RespBankSheetB9Z1github.com/shadiestgoat/bankDataDB/pb/bank_svc_pbʵ\x03\x02\b\x01b\beditionsp\xe9\az\x0epatch/go.proto"

var file_bank_data_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_bank_data_proto_goTypes = []any{
	(*RespNew)(nil),                // 0: main.RespNew
	(*ReqDelete)(nil),              // 1: main.ReqDelete
	(*ReqBankSheet)(nil),           // 2: main.ReqBankSheet
	(*RespBankSheet)(nil),          // 3: main.RespBankSheet
	(*mappings.ReqList)(nil),       // 4: mappings.ReqList
	(*mappings.ReqNew)(nil),        // 5: mappings.ReqNew
	(*mappings.Mapping)(nil),       // 6: mappings.Mapping
	(*mappings.ReqDelete)(nil),     // 7: mappings.ReqDelete
	(*categories.ReqList)(nil),     // 8: categories.ReqList
	(*categories.ReqNew)(nil),      // 9: categories.ReqNew
	(*categories.Category)(nil),    // 10: categories.Category
	(*transactions.ReqList)(nil),   // 11: transactions.ReqList
	(*transactions.ReqNew)(nil),    // 12: transactions.ReqNew
	(*transactions.ReqUpdate)(nil), // 13: transactions.ReqUpdate
	(*cards.ReqList)(nil),          // 14: cards.ReqList
	(*cards.ReqNew)(nil),           // 15: cards.ReqNew
	(*cards.Card)(nil),             // 16: cards.Card
	(*mappings.RespList)(nil),      // 17: mappings.RespList
	(*mappings.RespNew)(nil),       // 18: mappings.RespNew
	(*emptypb.Empty)(nil),          // 19: google.protobuf.Empty
	(*mappings.RespDelete)(nil),    // 20: mappings.RespDelete
	(*categories.RespList)(nil),    // 21: categories.RespList
	(*transactions.RespList)(nil),  // 22: transactions.RespList
	(*transactions.RespNew)(nil),   // 23: transactions.RespNew
	(*cards.RespList)(nil),         // 24: cards.RespList
}
var file_bank_data_proto_depIdxs = []int32{
	4,  // 0: main.BankData.MappingsList:input_type -> mappings.ReqList
	5,  // 1: main.BankData.MappingsNew:input_type -> mappings.ReqNew
	6,  // 2: main.BankData.MappingsUpdate:input_type -> mappings.Mapping
	7,  // 3: main.BankData.MappingDelete:input_type -> mappings.ReqDelete
	8,  // 4: main.BankData.CategoriesList:input_type -> categories.ReqList
	9,  // 5: main.BankData.CategoriesNew:input_type -> categories.ReqNew
	10, // 6: main.BankData.CategoriesUpdate:input_type -> categories.Category
	1,  // 7: main.BankData.CategoriesDelete:input_type -> main.ReqDelete
	11, // 8: main.BankData.TransactionsList:input_type -> transactions.ReqList
	12, // 9: main.BankData.TransactionsNew:input_type -> transactions.ReqNew
	13, // 10: main.BankData.TransactionsUpdate:input_type -> transactions.ReqUpdate
	1,  // 11: main.BankData.TransactionsDelete:input_type -> main.ReqDelete
	14, // 12: main.BankData.CardsList:input_type -> cards.ReqList
	15, // 13: main.BankData.CardsNew:input_type -> cards.ReqNew
	16, // 14: main.BankData.CardsUpdate:input_type -> cards.Card
	1,  // 15: main.BankData.CardDelete:input_type -> main.ReqDelete
	2,  // 16: main.BankData.UploadBankSheet:input_type -> main.ReqBankSheet
	17, // 17: main.BankData.MappingsList:output_type -> mappings.RespList
	18, // 18: main.BankData.MappingsNew:output_type -> mappings.RespNew
	19, // 19: main.BankData.MappingsUpdate:output_type -> google.protobuf.Empty
	20, // 20: main.BankData.MappingDelete:output_type -> mappings.RespDelete
	21, // 21: main.BankData.CategoriesList:output_type -> categories.RespList
	0,  // 22: main.BankData.CategoriesNew:output_type -> main.RespNew
	19, // 23: main.BankData.CategoriesUpdate:output_type -> google.protobuf.Empty
	19, // 24: main.BankData.CategoriesDelete:output_type -> google.protobuf.Empty
	22, // 25: main.BankData.TransactionsList:output_type -> transactions.RespList
	23, // 26: main.BankData.TransactionsNew:output_type -> transactions.RespNew
	19, // 27: main.BankData.TransactionsUpdate:output_type -> google.protobuf.Empty
	19, // 28: main.BankData.TransactionsDelete:output_type -> google.protobuf.Empty
	24, // 29: main.BankData.CardsList:output_type -> cards.RespList
	0,  // 30: main.BankData.CardsNew:output_type -> main.RespNew
	19, // 31: main.BankData.CardsUpdate:output_type -> google.protobuf.Empty
	19, // 32: main.BankData.CardDelete:output_type -> google.protobuf.Empty
	3,  // 33: main.BankData.UploadBankSheet:output_type -> main.RespBankSheet
	17, // [17:34] is the sub-list for method output_type
	0,  // [0:17] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_bank_data_proto_init() }
func file_bank_data_proto_init() {
	if File_bank_data_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bank_data_proto_rawDesc), len(file_bank_data_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bank_data_proto_goTypes,
		DependencyIndexes: file_bank_data_proto_depIdxs,
		MessageInfos:      file_bank_data_proto_msgTypes,
	}.Build()
	File_bank_data_proto = out.File
	file_bank_data_proto_goTypes = nil
	file_bank_data_proto_depIdxs = nil
}
